### ISSUE TITLE
R Image & Python image

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-containers#1]
This image is more-or-less working I think, but I'll need to push it to a public registry unless we add kubeflow authorization to the container registry

https://github.com/blairdrummond/kubeflow-daaas-images/blob/master/R2/Dockerfile

This one is most of the way there, but there seems to be some incompatibility with keras

https://github.com/blairdrummond/kubeflow-daaas-images/blob/master/data-science/Dockerfile

**Comment by sylus** [comment]
Hey so I was hoping we could look over these container images and make improvements and maybe if I can understand a bit can offer some improvements. So right now we are just deploying the bare minimum repositories as I wanted to get that working before added customizations and to see what the base size is.

First from the perspective of r:

a) Why weren't you using r-notebook since the notebook is supposed to be for r?
b) What would you consider the absolute bare minimum that should be added to these notebooks?

**Comment by blairdrummond** [comment]
a) If possible it's nice to have Python R and Julia. The R image actually has all three, it's just tuned to R and had R-based geomatics packages. (whereas it doesn't include the python ML libraries). It's about 8gb too, so I thought the size was reasonable.

b) It's a little hard for me to say, but basically the two camps are the Python and R people. The python folks here mostly use PyTorch & XGBoost I think it's probably good to have TF and Keras too.

With respect to the sizes, I think part of the issue might have been too many layers (I compiled many things on seperate lines to avoid recompiling when something inevitably broke), and I started invoking `conda clean` to clean up space.

PR coming in in a second, it just finished compiling.

**Comment by sylus** [comment]
Hey @blairdrummond I did some work on your r-notebook trying to follow the same convention as jupyter. Think got everything you mentioned, looks good?

https://github.com/StatCan/kubeflow-containers/blob/master/r-notebook/base/Dockerfile

**Comment by sylus** [comment]
At @blairdrummond I started working on the cpu tensorflow-notebook.

Can you give me a list here of what is missing? Keeping as simple as possible

https://github.com/StatCan/kubeflow-containers/blob/master/tensorflow-notebook/base/Dockerfile.cpu

**Comment by blairdrummond** [comment]
Oh ha, I just wrote one of those too

https://raw.githubusercontent.com/blairdrummond/kubeflow-containers/new-images/tensorflow-notebook/all-dressed/Dockerfile.cpu

That image looks good for a Tensorflow base. The image I have here has the extra ML libraries. I'm building it now (my poor computer is slow at building them), will confirm when it finishes building.

How does it look?

**Comment by blairdrummond** [comment]
FYI, still working on this. Trying to keep a tidy style, just iterating on some things...

**Comment by blairdrummond** [comment]
Want to take a look at this one?

https://github.com/blairdrummond/kubeflow-containers/blob/new-images/tensorflow-notebook/all-dressed/Dockerfile.cpu

It's more-or-less finished building. I ran it and it failed at the `fix-permissions` line because I hadn't included that script. It's in there now, so I think the main layer should build
