### ISSUE TITLE
torch tools

### ISSUE THREAD

**Issue by chritter** [StatCan/kubeflow-containers#10]
Hello @sylus,@blairdrummond,

We would need the torchvision and torchtext Python packages for PyTorch.

Thank you.

Moved from https://github.com/StatCan/terraform-kubernetes-aks-platform-daaas/issues/10#event-3211858053

**Comment by chritter** [comment]
@blairdrummond Based on the referenced issue, could you clarify if this is done already?

**Comment by blairdrummond** [comment]
Torchtext had an error on the first install. It needs to be installed with

`conda install -c pytorch torchtext` 

Torchvision is installed

**Comment by chritter** [comment]
Great. Thank you.

**Comment by sylus** [comment]
Hey torchtext currently isn't since failed will have to still add.

**Comment by sylus** [comment]
Generating a build with this now :) 

https://github.com/StatCan/kubeflow-containers/actions/runs/74070128
