### ISSUE TITLE
remote-desktop-experimental: Add CUDA

### ISSUE THREAD

**Issue by frazs** [StatCan/kubeflow-containers#100]
A quick test of adding CUDA drivers (+ toolkit? + cudnn? +torch.cuda?) to the experimental remote-desktop to see if that satisfies the prerequisites for further extensions implemented by @chritter's team. 

Relating to https://github.com/StatCan/kubeflow-containers/issues/37 progress here may be rolled into a future GPU flavor of Remote Desktop.

**Comment by frazs** [comment]
@chritter Try `k8scc01covidacr.azurecr.io/remote-desktop-test:allinone-gpu` and let me know any feedback. It includes everything in https://github.com/ml-tooling/ml-workspace/blob/master/gpu-flavor/Dockerfile

**Comment by chritter** [comment]
@frazs Thank you. The pod is not able to get beyond the initialization stage.

**Comment by chritter** [comment]
@frazs I found that the installed CUDA drivers work for us with the following config:
`torch==1.4.0`
`torchvision==0.5.0`

Setup Details:

```text
=== Software === 
python        : 3.7.7
fastai        : 1.0.58
fastprogress  : 0.2.7
torch         : 1.4.0
torch cuda    : 10.1 / is available
torch cudnn   : 7603 / is enabled

=== Hardware === 
torch devices : 1
  - gpu0      : Tesla V100-PCIE-16GB

**Comment by chritter** [comment]
I will proceed using your image as a base image.

**Comment by frazs** [comment]
@chritter FYI there is a minor issue in this image (and possibly the other experimental ones) where the desktop launchers for RStudio and QGIS are missing. However, both programs are still present. The desktop launchers can be added back by right clicking on the desktop, selecting `Create Launcher`, and typing in qgis or rstudio (there will be an autocomplete option that will fill in all the other necessary information). The first time either is launched there will also be a prompt to mark the launcher as executable.

I am not yet sure what causes this.

**Comment by frazs** [comment]
Found the cause: the QGIS and RStudio installers make their desktop launchers in `/tmp/home_nbuser_default` but various pieces of cleanup code for the GPU components wipe all of /tmp/. This affects the QGIS and RStudio launchers as well as the VS Code Python extension fix on the experimental images only. I think this is best tackled with a refactor on the official images so that `home_nbuser_default` is no longer in `/tmp/` (as this is not the first time something has interfered with it), along with a rebase for the experimental image.

Since that is time consuming, and the desktop launcher recreation + VS Code Python extension downgrade can be fixed in the container by a regular user, I suggest doing that for now, unless other issues are discovered that interfere with functionality and cannot be resolved without a rebuild.

Alternatively for a temporary workaround, if you are building on top of this image anyway, you could throw in the following code near the end (of your image that uses `allinone-gpu` as a base) next time you rebuild until this is resolved. It should work since it will execute after any `/tmp/` clears.

```
RUN echo "[Desktop Entry]
	Version=1.0
	Type=Application
	Name=QGIS Desktop
	Comment=
	Exec=/usr/bin/qgis %F
	Icon=qgis
	Path=
	Terminal=false
	StartupNotify=false" >> "/tmp/home_nbuser_default/Desktop/QGIS Desktop.desktop" && \
    chmod +x "/tmp/home_nbuser_default/Desktop/QGIS Desktop.desktop" && \
    chown ${NB_USER}:${NB_USER} "/tmp/home_nbuser_default/Desktop/QGIS Desktop.desktop" && \
    echo "[Desktop Entry]
	Version=1.0
	Type=Application
	Name=RStudio
	Comment=
	Exec=/usr/lib/rstudio/bin/rstudio %F
	Icon=rstudio
	Path=
	Terminal=false
	StartupNotify=false" >> "/tmp/home_nbuser_default/Desktop/RStudio.desktop" && \
    chmod +x "/tmp/home_nbuser_default/Desktop/RStudio.desktop" &&\
    chown ${NB_USER}:${NB_USER} /tmp/home_nbuser_default/Desktop/RStudio.desktop

ARG SHA256py=a4191fefc0e027fbafcd87134ac89a8b1afef4fd8b9dc35f14d6ee7bdf186348
ARG VS_PYTHON_VERSION=2020.5.86806
RUN rm -rf /tmp/home_nbuser_default/.vscode/extensions/ms-python.python-2020.6.91350 && \
    wget --quiet --no-check-certificate https://github.com/microsoft/vscode-python/releases/download/$VS_PYTHON_VERSION/ms-python-release.vsix && \
    echo "${SHA256py} ms-python-release.vsix" | sha256sum -c - && \
    bsdtar -xf ms-python-release.vsix extension && \
    rm ms-python-release.vsix && \
    mv extension /tmp/home_nbuser_default//.vscode/extensions/ms-python.python-$VS_PYTHON_VERSION
```

**Comment by chritter** [comment]
@frazs The image serves our needs very well. This issue could be closed.

**Comment by frazs** [comment]
Great! 😀
