### ISSUE TITLE
Xeus Python kernel's autocomplete not working correctly

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/kubeflow-containers#108]
Autocomplete not fully working. Should be able to type something like "myClass." (with or without a tab after) and get autocomplete for methods.  Some other autocomplete's within the kernel are working ok, but not this type

**Comment by Ito-Matsuda** [comment]
Hi @ca-scribner could I ask you to clarify the autocomplete? I start up the xpython  notebook/console and I can get the [following](https://imgur.com/a/E4ZQNi7). It does not appear to auto-complete unless you really go for the double-tab.

**Comment by ca-scribner** [comment]
hmm ok maybe it just needs a double-tab and I never did, that or maybe some of the version bumps saffa has done might have fixed it?  Looks like we can just close this then!

**Comment by Ito-Matsuda** [comment]
Closing as it seems to be fixed. 
May need to double tab to get the code completion suggestion to show up.
