### ISSUE TITLE
Kubeflow Pipelines

### ISSUE THREAD

**Issue by chritter** [StatCan/kubeflow-containers#11]
Hello,

To enable the usage of KF Pipelines could you install the python packages kfp and
specifically afterwards

```kfp-server-api==0.1.18.3```

due to a bug in KF.

Thank you.

**Comment by blairdrummond** [comment]
Yep, can do. I'll do a PR tomorrow.

**Comment by sylus** [comment]
Generating a build with this now :) 

https://github.com/StatCan/kubeflow-containers/actions/runs/74070128

**Comment by chritter** [comment]
@sylus The bug is still present and the kfp package does not work correctly. After installing `pip install kfp-server-api==0.1.18.3` I could resolve this issue. Have you installed `pip install kfp-server-api==0.1.18.3` after `pip install kfp`, as I did?

**Comment by sylus** [comment]
I read your issue and assumed anything after that version would fix?

Here is how I ran it: 

https://github.com/StatCan/kubeflow-containers/blob/master/base-notebook/cpu/Dockerfile#L8

It should be using a version way later then thatm can you point to the bug talking about?

**Comment by sylus** [comment]
Looks like this is fixed now :D
