### ISSUE TITLE
Packages and extensions installed twice in dockerfile stack

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/kubeflow-containers#110]
Check if any `Python`, `R`, and `Jupyterlab` extensions/packages are installed twice.

For `Jupyterlab` extensions, `jupyter-widgets/jupyterlab-manager` is installed twice. 
Remove the latest one?  Or is this for a version bump?

Hold off on GPU images for now because of https://github.com/StatCan/kubeflow-containers/issues/107

**Comment by saffaalvi** [comment]
`r-studio` -> `minimal-notebook/cpu` -> `base-notebook/cpu` -> [`datascience-notebook`](https://github.com/jupyter/docker-stacks/blob/04f7f60d34a674a2964d96a6cb97c57a7870a828/datascience-notebook/Dockerfile) 

A lot of packages installed in `r-studio` have already been installed in `datascience-notebook` but without versions specified (so latest version will be installed). 

Will remove duplicates or decide which package is needed when looking at the pinning versions issue (https://github.com/StatCan/kubeflow-containers/issues/106).
