### ISSUE TITLE
[Epic] Clean up Jupyter Image Dockerfile Stack

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/kubeflow-containers#112]
Tracker issue for related jupyter server image cleanup.  These issues are to reduce duplication/chance of breakage in our jupyter server images.  Note that this should be done by the same person or in coordination with #111 as they overlap.  More discussion in StatCan/kubeflow-containers#102.

* [x] #105 Remove Dremio/Pachyderm
* [ ] #107 Refactor notebook images to keep cpu/gpu in sync and make the stack more maintainable

**Comment by DavidSpek** [comment]
I'm not sure if this is of interest, as it looks like custom base images are used. However, it is possible to use regular upstream jupyter images with kubeflow as only the `CMD` needs to be changed for support. The minimum I have found to be necessary is:

```
ARG BASE_CONTAINER=jupyter/datascience-notebook
FROM $BASE_CONTAINER

# Configure container startup
CMD ["sh","-c", "jupyter lab --NotebookApp.token='' --NotebookApp.base_url=${NB_PREFIX}"]
```
However, to keep it the same as what Kubeflow user now it would be:

```
ARG BASE_CONTAINER=jupyter/datascience-notebook
FROM $BASE_CONTAINER

# Configure container startup
CMD ["sh","-c", "jupyter lab --notebook-dir=/home/${NB_USER} --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]
```
This version does have some redundant options that are already default being passed though.

**Comment by ca-scribner** [comment]
Thanks @DavidSpek, I'll try this out!

**Comment by DavidSpek** [comment]
This might also be of interest to you. https://github.com/kubeflow/kubeflow/issues/2208
As you can see some people are also wanting to look into having support for RStudio and Theia (and VS Code server). I believe you have already created a version of RStudio that supports Kubeflow. Your method of creating this might help to determine how best to add support for RStudio and other Web-IDEs as well.

**Comment by DavidSpek** [comment]
@ca-scribner Not sure if this is interesting for you guys, but I created an image based on the upstream datascience-notebook with both VS Code and RStudio, inspired by your work as well as this [comment](https://github.com/kubeflow/kubeflow/issues/3362#issuecomment-702559949). 

```
ARG BASE_CONTAINER=jupyter/datascience-notebook
FROM $BASE_CONTAINER

USER root

# Install VS Code
RUN curl -fsSL https://code-server.dev/install.sh | sh

# Install RStudio dependency
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    gdebi-core

ENV RSTUDIO_VERSION 1.1.463

# Install RStudio and another dependency
RUN wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.4_amd64.deb -O libssl1.0.0.deb && \
    dpkg -i libssl1.0.0.deb && \
    curl -fsSL "https://download2.rstudio.org/rstudio-server-${RSTUDIO_VERSION}-amd64.deb" > /tmp/rstudio.deb && \
    apt-get install --no-install-recommends -y /tmp/rstudio.deb && \
    rm /tmp/rstudio.deb && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER $NB_UID

# Install jupyter proxies for VS Code and RStudio
RUN pip3 install jupyter-server-proxy && \
    pip3 install jupyter-vscode-proxy && \
    pip3 install jupyter-rsession-proxy && \
    jupyter labextension install @jupyterlab/server-proxy

# Configure container startup
CMD ["sh","-c", "jupyter lab --notebook-dir=/home/${NB_USER} --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]
```
