### ISSUE TITLE
Tensorflow does not work in machine-learning-notebook (and others?)

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/kubeflow-containers#121]
Running something like 
```
import tensorflow as tf
tf.test.is_gpu_available(
    cuda_only=False, min_cuda_compute_capability=None
)
```
returns the message `AttributeError: module 'tensorflow' has no attribute 'test'`.  This is repeated for anything `tf.*`.  Similar issues pop up if using `kubeflow metadata`/`ml medatada`, likely for the same reason.

Can be fixed by 
```
pip uninstall tensorflow  # Note this is 2.1.0 as of writing
pip uninstall tensorflow-estimator
pip install tensorflow==2.3.0
```
Unsure if this fix works because we're installing a different version, or if the 2.1.0 install is corrupt in general?  Tensorflow gets installed by accident in `base-notebook` when installing `kubeflow-metadata`, so that might be related?

**Comment by saffaalvi** [comment]
This may have been fixed when the Tensorflow package was updated to version 2.2.0:
 https://github.com/StatCan/kubeflow-containers/blob/423b70c25f67e66698f54d0d849652ddd280e795/machine-learning-notebook/cpu/Dockerfile#L7

Now, when I run the command you gave as an example, there is no more error but instead just a deprecation warning (only shows up the first time it's ran):
```
WARNING:tensorflow:From <ipython-input-1-a32398aaaac2>:2: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
False
```
![Screen Shot 2020-10-19 at 12 46 00 PM](https://user-images.githubusercontent.com/57377830/96481176-2fbf3d80-1209-11eb-89ca-8071884c5a09.png)

Tensorflow is also no longer installed in `base-notebook ` (also a result of version update), so the only notebook that has it installed is `machine-learning-notebook/cpu`.

**Comment by saffaalvi** [comment]
Tested out [kubeflow-metadata demo](https://github.com/StatCan/jupyter-notebooks/blob/2b40391ec0b4a8fc795baedc124f572f6b97a0c7/kubeflow-metadata/overview.ipynb)  on custom image: machine-learning-notebook-cpu:129ee3e50de291c4fe65397a614f5cccb379d5fd with the latest version updates. 

Everything seems to be working well so this issue will be resolved when latest image commits are updated in kubeflow-manifest.

**Comment by ca-scribner** [comment]
This issue is affecting our `machine-learning-notebook` image again.  Hilariously, `base-notebook` and `minimal-notebook` both have working tensorflow! :)

I believe this is because in `base-notebook` we install `kubeflow-metadata` which requires `ml-metadata==0.21.0` which has a tensorflow dependency, resulting in us installing unexpectedly.  This dependency on tf is removed in `ml-metadata==0.23.0`, but `kf-metadata` hasn't updated to the newer `ml-metadata` yet).

To fix temporarily, I think we can remove the `tensorflow` install from `machine-learning-notebook` and it'll work fine.  We should add an explicit `tensorflow` install in `base-notebook` above the `kubeflow-metadata` install to make it clear we install tf there, and a note saying when `kubeflow-metadata` updates to `ml-metadata>=0.23.0` that we should remove our tf install and put it back in the `machine-learning-notebook`.

**Comment by ca-scribner** [comment]
TF is working in cpu images but not gpu images.  This difference appears to be because tf in cpu is `2.3.1` and in gpu is `2.1*`
