### ISSUE TITLE
Docker images still push to acr even when scan flags as unsafe

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/kubeflow-containers#125]
For each image, current build/deploy CI does:

* `docker build` image
* `docker push` image (to acr)
* `scan` image
  * if scan fails: fail entire build and stop entire process
  * if scan succeeds: continue build process

This results in all images built, regardless of whether they're safe, to be publicly accessible from the platform (and publicly viewable here in the github actions log, which states that they failed due to a security vulnerability and states their build image name).

Possible solutions:

1. refactor CI to:
  * `docker build` image
  * `scan` image
    * if scan succeeds: `docker push` to acr
    * if scan fails: do not push.  Optionally could fail entire build or still build other images
2. refactor CI do:
  * `docker build` image
  * `docker push` image (to acr)
  * `scan` image
    * if scan fails: delete pushed image to acr.  Optionally could fail entire build or still build other images
    * if scan succeeds: continue build process

If doing option (2), we could also use `acr build` instead of `docker build`/`docker push`, so long as we either delete the image from `acr` if it fails scan or follow a pattern of:
*  `acr build` into a quarantined space
*  scan
  * if succeeds, copy to public space

**Comment by ca-scribner** [comment]
Another option would be to have two `acr`s: `dev` (or `unscanned`) and `prod`, where images first go into `unscanned` then only safe images go to `prod`:
3. refactor CI to do:
* `docker build` image
* `docker push` image (to **restricted access** acr, say `unscanned-containers`)
* `scan` image:
  * if scan succeeds: `acr cp` image from `unscanned-containers` to usual acr location

If we can restrict notebook servers to only let developers pull custom images from the `unscanned` repo then devs can still interact with those unsafe notebooks, but only the safe ones are accessible to the public.  It would also help with notebook cleanup (unused dev images are easier to find).

This could make for a good development workflow too.  `dev`/`unscanned` notebooks initially go into `unscanned`, then developers can interact with them there and test on the platform without regular users being able to access them.  Once the images are good to go they can go into regular `prod` repo and all users have access.

**Comment by ca-scribner** [comment]
@brendangadd thoughts?  Am I overthinking this one?

**Comment by ca-scribner** [comment]
@blairdrummond cc

**Comment by brendangadd** [comment]
@ca-scribner I added a PR for the extra ACR, but I'd like to restrict that to situations where developers really need to test something in the cluster. In general, I like your solution (1): don't push images that have known vulnerabilities.

**Comment by ca-scribner** [comment]
waiting on #146 which is also a pretty big architectural change

**Comment by blairdrummond** [comment]
Closed by #163
