### ISSUE TITLE
Update or remove tekton from notebook images?

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/kubeflow-containers#131]
Do we use the tekton DSL (kfp-tekton)?  If yes, current install (v0.2.0) in the notebooks is incompatible with our kubeflow version (wants kf<0.5, we have >1.0).  We should either update it or remove

**Comment by JessicaBarh** [comment]
latest kfp-tekton is v0.17.0

**Comment by ca-scribner** [comment]
I have a feeling nobody uses this, but I don't know it for sure
