### ISSUE TITLE
pyarrow

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-containers#14]
Might be something worth looking into? I will look into it. (Lower priority, obviously)

**Comment by brendangadd** [comment]
@blairdrummond Can you please provide some more context? My understanding is that users can grab `pyarrow` via `pip`.

**Comment by blairdrummond** [comment]
`pyarrow` is an interface for C++ stuff, so pip install won't cut it. `conda` might handle everything, but want to test to see if there are `apt` level packages that need to be installed for those to work.
