### ISSUE TITLE
base-notebook-gpu build fails

### ISSUE THREAD

**Issue by saffaalvi** [StatCan/kubeflow-containers#140]
When trying to build `base-notebook-gpu`, the following error stops the image from building at Step 10/70:

```
Fetched 21.6 MB in 3s (7711 kB/s)
Reading package lists...
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/developer.download.nvidia.com_compute_cuda_repos_ubuntu1804_x86%5f64_Packages.lz4
E: The package lists or status file could not be parsed or opened.
The command '/bin/sh -c apt-get update  && apt-get install -yq --no-install-recommends     wget     bzip2     ca-certificates     sudo     locales     fonts-liberation     run-one  && apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

Error: Process completed with exit code 100.
```
No changes were made to `base-notebook-gpu` in the latest commit. Re-ran jobs for the last successful commit and even that now fails.

**Comment by sylus** [comment]
Thinking this looks like one of the recent additions as I didn't do it hard for me to debug.

Assigning to Andrew to take a look if ok?

**Comment by ca-scribner** [comment]
I'll dig into it with @saffaalvi , but talking with Saffa yesterday it sounded like images that used to build now break with this error so it is probably upstream

**Comment by ca-scribner** [comment]
restarted the CI and it looks like it made it past that step.  Maybe a download failed or something yesterday?  Let's see if it finishes

**Comment by saffaalvi** [comment]
All checks have passed on the most recent build, so like @ca-scribner said, might have been a download fail that's working now.
