### ISSUE TITLE
Add i18n to JupyterLab

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-containers#148]
Look into whether the JupyterLab UI can be offered in other languages.

- [x]  i18n (including extensions) - finish FR language pack + use KF_LANG to set language on startup
- [ ]  ~~Debugger - xpython~~
- [x]  Extensions - use compatible versions
- [ ]  Docker Stacks - check for new release wih Jupyterlab 3.0.  upstream issue: https://github.com/jupyter/docker-stacks/issues/1207

**Comment by wg102** [comment]
The feature **i18n and i10n** (https://github.com/jupyterlab/jupyterlab/issues/3965) is  planned to be part of the **3.0 release** (https://github.com/jupyterlab/jupyterlab/issues/8038), which has no clear release date. 
The i18n PR is rather extensive (https://github.com/jupyterlab/jupyterlab/pull/8800).

The second part is having the translations, this is the issue for the Translations https://github.com/jupyterlab/jupyterlab/issues/8829
which mentions the translations are done through crowdin. We will need those to be completed before we can use the language pack. https://crowdin.com/project/jupyterlab

I suggest to wait until this is merged and released before investigating if all our needs are met, and how to set the languages we want.

**Comment by JessicaBarh** [comment]
Official language packs have not yet been released (https://github.com/jupyterlab/language-packs/issues/11)

Once release, they can be installed with:
```bash
conda install -c conda-forge jupyterlab-language-pack-zh-CN  
#zh-CN = Chinese, replace with the required language pack code
```
or
`pip install jupyterlab-language-pack-zh-CN`

**Comment by JessicaBarh** [comment]
| Extension | Status | Translated |
| ---------- | ------- | ------------|
| @hadim/jupyter-archive@3.0.0 | OK | N |
| @jupyterlab/server-proxy@2.1.2 | OK | not required |
| @jupyterlab/toc@5.0.3 | OK | not required  |
| @jupyterlab/translation-extension@3.0.2 | OK    | Y   |
| @krassowski/jupyterlab-lsp@3.0.0 | OK | not required  |
| @lckr/jupyterlab_variableinspector@0.4.0 | OK | N |
| jupyter-matplotlib@0.7.4 | OK | not required |
| jupyterlab-plotly@4.14.3 | OK | TBD   |
| nbdime-jupyterlab@2.1.0-beta.1 | OK | TBD |
|   |
| @ijmbarr/jupyterlab_spellchecker@0.2.0 | no supported version |   |
| @jupyterlab/github@2.0.0 | no supported version, PR   |   |
| @jupyterlab/git@0.23.2 | no supported version, PR |   |
| jupyterlab-execute-time@1.0.0 | no supported version  |   |
| jupyterlab-theme-solarized-dark@1.0.3 | no supported version  |   |
| jupyterlab-spreadsheet@0.3.2 | no supported version   |   |
| kubeflow-kale-labextension@0.6.0 | no supported version   |   |

**Comment by sylus** [comment]
@JessicaBarh it seems jupyterlab-theme-solarized-dark is supported on the 3.0.x line?

However I don't even think we use it anymore (not using solarized):

https://github.com/StatCan/kubeflow-containers/blob/master/resources/jupyterlab-overrides.json

**Comment by sylus** [comment]
@blairdrummond did we also add the french language pack for code-server (vscode)?

**Comment by blairdrummond** [comment]
@Ito-Matsuda  has been looking at that I think?

**Comment by Ito-Matsuda** [comment]
I added it for [kubeflow-containers-desktop](https://github.com/StatCan/kubeflow-containers-desktop/issues/47) yes. (Note that this PR incorrectly used the Microsoft marketplace version. I later made a PR to fix that by grabbing and building the extension from the French Language package git repo)

**Comment by blairdrummond** [comment]
@Ito-Matsuda would you be able to take on that functionality for the kubeflow-containers? Should be the same process right?

**Comment by Ito-Matsuda** [comment]
Yea adding it should be no problem.

**Comment by Ito-Matsuda** [comment]
@blairdrummond this is just _adding_ the language pack correct? I'm looking at how we installed the `python` and `r` extension and after testing adding the following
`code-server --install-extension MS_CEINTL.vscode-language-pack-fr` 
get's the job done and the French language pack is installed.
