### ISSUE TITLE
VSCode server in jupyterlab images cannot find/install vs code extensions

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/kubeflow-containers#171]
From VSCode in a jupyterlab image, the `Extensions Marketplace` (widget on left bar) says "We cannot connect to the Extensions Marketplace at this time, please try again later."

**Comment by sylus** [comment]
@blairdrummond can u look at this?

**Comment by sylus** [comment]
Ok even with updating it seems this is a CORS issue with the redirect but fix is documented here:

https://github.com/cdr/code-server/issues/1370

Need to add this as a pod default and should have this fixed.

**Comment by sylus** [comment]
This now works.
