### ISSUE TITLE
Add VSCode Extensions to jupyterLab

### ISSUE THREAD

**Issue by Nancy-Badran** [StatCan/kubeflow-containers#178]
Extensions to be added : Python , R , Git as a baisc ones . Kubernetes , Docker as proposed ones.

**Comment by sylus** [comment]
I added both python and R and git is already part of the source code func in vscode so think that is solved.

Not sure of the utility of docker, kubernetes but I could be missing something so maybe as a new issue?

Fixed here and also corrected for the persistent directory issue:

https://github.com/StatCan/kubeflow-containers/commit/ecb85a690f9e6d0a0983b103c365c0eba7c1368c
