### ISSUE TITLE
request for RStudio

### ISSUE THREAD

**Issue by chritter** [StatCan/kubeflow-containers#18]
Hello,

With ml-workspace being enabled it would be great have RStudio as a default installation on the images.

Thank you.

**Comment by frazs** [comment]
On ml-workspace by default, R-Studio Desktop and Server are both available as installation scripts in the tools folder. Is that sufficient, or would you like them to be pre-installed for everyone?

If you would like them to be pre-installed, should that be R-Studio Desktop, R-Studio Server, or both?

**Comment by blairdrummond** [comment]
If I had to guess @frazs  I would guess that R-Studio Server won't work well in the network. I think probably just R-Studio Desktop.

Also, people LOVE R-Studio, so that would be a great addition.

**Comment by brendangadd** [comment]
Closing: this was merged into `non-root-manual-build` (not `master`).
