### ISSUE TITLE
Automate setup/refresh of MinIO credentials

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/kubeflow-containers#189]
MinIO credentials are mounted to notebook/pipeline pods in `/vault/secrets`.  These credentials have lifespans (1 day?  1 week? 
 can't remember) and are refreshed periodically for pods as they're running.  

Current recommendations for using MinIO are to `source /vault/secrets/...` to set up a single MinIO setup with the current MinIO credentials whenever users need them.  This causes issue because:
* It is a chore that is a barrier to entry for using MinIO (users must know how to set up MinIO, extra tasks for every use, etc)
* When credentials become stale this must be redone manually

# Proposal: 

Somehow automate the setup/refreshing of MinIO credentials so that users do not need to do this themselves.  Some possible ideas:
* A background process running on all notebook servers/pipeline components that watches for changes to `/vault/secrets/...` and  communicates them to MinIO (either directly into the `~/.mc/config.json` file, or maybe using MinIO interface `mc config host add ...`?)
* Configure MinIO to use a `config.json` file that Vault updates directly, negating the need for a watcher process
* ...?

**Comment by ca-scribner** [comment]
@blairdrummond anything to add?

**Comment by blairdrummond** [comment]
Another possible approach would be to simply wrap the `mc` client itself. For example, move `mc` to `/usr/local/bin/mc-wrapped` and write this to `/usr/local/bin/mc`

```
#!/bin/bash

for tenant in standard premium; do
    if [ ! -f /tmp/.minio-$tenant ] || [ /vault/secrets/minio-$tenant-tenant-1 -nt /tmp/.minio-tenant ]; then
        source /vault/secrets/minio-$tenant-tenant-1
        mc config host add $tenant $MINIO_URL $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
        touch /tmp/.minio-$tenant
    fi
done

/usr/local/bin/mc-wrapped $@
```

So every invocation of mc will just reconfigure itself

**Comment by blairdrummond** [comment]
Plus side of that approach is that there's no need to muck with vault, no daemons, etc

**Comment by ca-scribner** [comment]
Yeah that's nice, agreed

**Comment by blairdrummond** [comment]
Want to set the assignee? I think this sounds like a fast fix. We can also tidy up this file that way:

https://github.com/StatCan/kubeflow-containers/blob/c945134090ced7927106e7182f9dc7f879b209e1/resources/helpers.sh#L4-L11

**Comment by ca-scribner** [comment]
That is a Brendan question :)  Poke him in the planning

**Comment by Nancy-Badran** [comment]
Following the suggestion of @blairdrummond , I add the bash script check-tenant.sh to checks if the tenant if newer than a little "lockfile" . By running it this way, every time that the user calls mc, the for loop checks to see if any vault secrets are newer than the most recent lockfile. If the secret is newer, then it reinitializes the client right away.

**Comment by ca-scribner** [comment]
github auto closed this issue on PR.  @Nancy-Badran please test to confirm this is fully working and if not reopen this issue
