### ISSUE TITLE
[Epic] Update remote desktop images

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/kubeflow-containers#190]
It is desirable to update our remote desktop image such that it is less complex, more robust, and easier to maintain.  This may involve removing unused tools, changing the basic architecture, etc.

To do this, we need:
* [ ] Define user requirements for the image (consult Christian, internal team)
* [ ] Define what/how to keep common between remote desktop and kubeflow-container images (can we use the same mixins)
* [ ] Implementation

**Comment by blairdrummond** [comment]
Also worth noting, the jupyter-proxy things are pretty easy to set up (What drives VS-Code inside JupyterLab). It might be possible for us to somehow include a vnc session within JupyterLab.

**Comment by blairdrummond** [comment]
Closed by #250 after consultations with folks
