### ISSUE TITLE
Discuss the future of remote desktop

### ISSUE THREAD

**Issue by Jose-Matsuda** [StatCan/kubeflow-containers#194]
A place to document what is desired out of a more maintainable remote desktop image. This image would be a _pure_ desktop experience.
Questions to ask:
1) What functionality do we want to keep from the current remote-desktop solution hosted at [kubeflow-containers-desktop](https://github.com/StatCan/kubeflow-containers-desktop).
2) What functionality would be nice to have? 

Expand here / have meeting notes here...
Related to epic #190

**Comment by Ito-Matsuda** [comment]
@blairdrummond @brendangadd @ca-scribner @chritter I'd like to set up a meeting sometime to flesh out the details of this. What days and times work well for you?

**Comment by ca-scribner** [comment]
My outlook calendar should be accurate. Any time free in there works for me

**Comment by Ito-Matsuda** [comment]
Result of this first meeting.
A basic desktop minimal desktop experience, will contain applications like the desktop installations of VsCode, QGIS.
The reasoning is for people who need QGIS (desktop only) and for people who want a regular desktop experience. 


Actionable items on my end:
Make a minimal dockerfile with xfce4 and **VNC** connecting capabilities. Once I have one up and working, can look at integrating it with current `docker-bits` scheme.
