### ISSUE TITLE
VSCode in Jupyterlab does not run/debug python files out of the box

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/kubeflow-containers#198]
go to Jupyterlab server (CPU, etc) --> VS Code (button in the jupyterlab landing page)

Create a python file
```
print("Hello, World!")
```

Then try to run it or debug it by right click or run/debug from the menus.  File does not run.

In contrast, doing this from a remote desktop->VSCode works fine

**Comment by DavidSpek** [comment]
@ca-scribner, I believe this PR might be of interest to you: https://github.com/kubeflow/kubeflow/pull/5571. Similarly, https://github.com/kubeflow/kubeflow/pull/5570 is probably interesting for R-Studio. These methods do not rely on the `jupyterlab/server-proxy` or running alongside jupyterlab so it is more lightweight.

**Comment by ca-scribner** [comment]
Thanks @DavidSpek, looking forward to seeing what you're doing!  We've gone back and forth between shoehorning everything into jupyterlab via proxy and keeping things separate, never quite finding a way that felt perfect

**Comment by DavidSpek** [comment]
@ca-scribner There were some talks in the Kubeflow Notebooks working group about extending the Notebook controller to be a more general controller for applications similar to notebooks (so I guess any app with a web UI). Though it might be a while before that happens. 
May I ask how you were keeping things separate? Your experience can be quite valuable for creating better support for, initially, VS-Code and R-Studio. Also, sorry for hijacking the issue. You can hit me up on the Kubeflow slack as well.

**Comment by ca-scribner** [comment]
Fixed by #234
