### ISSUE TITLE
Previewing R shiny reports in jupyter lab

### ISSUE THREAD

**Issue by menmarc** [StatCan/kubeflow-containers#20]
Is it possible to import shiny reports into an R notebook and view them? In the example attached, I can run it but can't view it. I get a "Listening on http://127.0.0.1:someport'

Thanks!

[exampleReport2.zip](https://github.com/StatCan/kubeflow-containers/files/4530718/exampleReport2.zip)

**Comment by blairdrummond** [comment]
@sylus @zachomedia Do you know if it would be possible to direct a url to a fixed port on the notebook server? So people could always set up their service on port 9000 or something and access it through a browser?

The alternative is port-forwarding; but these seems tricky if they're not k8s-foo users making dashboards. This **would** be resolved, potentially, by tools like RStudio inside ML-Workspace.

**Comment by blairdrummond** [comment]
@menmarc Would this be addressed by #18 ? If so, would you mind closing this comment and adding a note to that issue?

**Comment by blairdrummond** [comment]
See also #32

**Comment by blairdrummond** [comment]
@brendangadd This will be resolved along with a fix to the Shiny Proxy. We have Shiny in the images, the only issue is that javascript assets don't seem to load properly.

**Comment by blairdrummond** [comment]
The Shiny extension seems to be working great out of R-Studio. I think we *can* add it to Jupyter as well, but this might be lower priority if we have it working in R-Studio.

What say you, @brendangadd ?

CC @menmarc

**Comment by brendangadd** [comment]
@blairdrummond We should keep this one open until previews are functioning in JupyterLab. But good for @menmarc to know there's a workaround via the R-Studio image.

**Comment by blairdrummond** [comment]
I think it's actually going to be a bit involved to run shiny. It seems like it requires a full R-Shiny server installed within the image, or R-Studio.

https://github.com/ryanlovett/jupyter-shiny-proxy#pre-reqs

I think it might make sense to leave this within R-Studio...

**Comment by brendangadd** [comment]
Ah, okay. We can close then. If we get enough demand for this in JupyterLab specifically, then we can take another look at if it's worth including R-Shiny in those images – and reopen if necessary.
