### ISSUE TITLE
Compare resource use and image size of jupyter-vnc vs regular vnc

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-containers#208]
@Ito-Matsuda it'd be good for record-keeping to check:

- Image Size
- Resource Usage

For a baseline vnc image (like the one from dockerhub) against our image that uses jupyter underneath.

**Comment by ca-scribner** [comment]
@blairdrummond mentioned the current jupyter version of the remote desktop feels laggy versus an nginx deployment.  Compare and decide if we should make changes

**Comment by blairdrummond** [comment]
Non issue. Image sizes are good enough
