### ISSUE TITLE
Fix Jupyter Server on non-OL images

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-containers#212]
At the moment only the OL images work on master, the rest have

```
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_core/command.py", line 133, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-server` not found.
```

It's as easy as pip installing jupyter_server to fix, but want to figure out whether that's the best option?

**Comment by JessicaBarh** [comment]
an alternative is to keep it as it was using `jupyter notebook` instead of `jupyter server` for non OL images. What do you think @blairdrummond ?

**Comment by JessicaBarh** [comment]
> an alternative is to keep it as it was using `jupyter notebook` instead of `jupyter server` for non OL images. What do you think @blairdrummond ?

this might also not be idea because it will require 2 seperate start-custom.sh scripts (one for OL one for non).

**Comment by blairdrummond** [comment]
Totally up to you. I think the best solution would be one where, when we upgrade the base image from docker-stacks, we don't even notice the change. I'm assuming all we'd need to do it install jupyter_server? But it's your call
