### ISSUE TITLE
Remote Desktop QGIS gdal failures

### ISSUE THREAD

**Issue by Ito-Matsuda** [StatCan/kubeflow-containers#216]
An offshoot of #204
![image](https://user-images.githubusercontent.com/23174198/107815549-882ec380-6d41-11eb-9431-7c22ef84644c.png)

Before this error, I needed to add a `/usr/lib/python3/dist-packages` to the path else it would not be able to find QGIS. 

I did some testing with our current remote desktop, and I cannot import fiona or geopandas in qgis but can import gdal.
![image](https://user-images.githubusercontent.com/23174198/107816277-85809e00-6d42-11eb-82ce-c2145bbe1f9e.png)
(if I use python from the cmd then yes I can)

Here's the [dockerfile](hhttps://github.com/StatCan/kubeflow-containers/blob/remote-desktop-test/output/RemoteDesktop/Dockerfile#L464) I've been trying to run with, I have just been doing changes in the 'output' folder for now just trying to get QGIS to start normally. Any of `fiona gdal` or `geopandas` installs causes then the topmost picture with 'No Module named' appears.

I can [uncomment this env LD_LIBRARY_PATH](https://github.com/StatCan/kubeflow-containers/blob/remote-desktop-test/output/RemoteDesktop/Dockerfile#L468) set and have QGIS load up fine (from the cmd) but it removes Thunar functionality (guessing i can set this another way and have it not interfere) 
![image](https://user-images.githubusercontent.com/23174198/107818230-4e5fbc00-6d45-11eb-981a-0cfb739ec990.png)

Note that if you do not include the conda install for fiona, gdal, and geopandas you can still import gdal from osgeo

**Comment by blairdrummond** [comment]
@Ito-Matsuda can you link the latest dockerfile you're using?

**Comment by blairdrummond** [comment]
Closed by #225
