### ISSUE TITLE
500 POST error message in jupyterlab

### ISSUE THREAD

**Issue by JessicaBarh** [StatCan/kubeflow-containers#218]
## Description
Inside a jupyterlab image the following error pops up:

![image](https://user-images.githubusercontent.com/71149531/107863973-12505800-6e26-11eb-8fc6-d919b3b09a80.png)

in console: 
500 POST /notebook/brendan-gadd/jupyter-feb/git/show_top_level?1613164707372 (127.0.0.1) 14.68ms referer=https://kubeflow.covid.cloud.statcan.ca/notebook/brendan-gadd/jupyter-feb/lab?

## Steps to Reproduce the Problem

  1. start a jupyterlab-cpu image
  1. print("Hello World") in a julia notebook 

there's something similar discussed in a jupyterlab-git issue: https://github.com/jupyterlab/jupyterlab-git/pull/855

**Comment by JessicaBarh** [comment]
jupyter-lsp 2.x supported language server does not include julia: https://jupyterlab-lsp.readthedocs.io/en/2.x/Language%20Servers.html

3.x does: https://jupyterlab-lsp.readthedocs.io/en/v3.4.0/Language%20Servers.html

but I think there's still a way to add it to 2.x manually in a config file -> https://jupyterlab-lsp.readthedocs.io/en/2.x/Configuring.html#Configuration-Options

**Comment by JessicaBarh** [comment]
using jupyterlab-git v0.22.0 vs 0.23.2 removes that pop-up error but there's still the message of "julia not supported yet" so still working on fixing that one

**Comment by JessicaBarh** [comment]
so my version of jupyterlab-lsp extension ended up working, I was just being impatient earlier.

![image](https://user-images.githubusercontent.com/71149531/108121198-69496d80-7070-11eb-8403-63af6e9ae266.png)

Should I still bother adding this to our jupyterlab 2 images? @brendangadd @blairdrummond

**Comment by blairdrummond** [comment]
I would still say just prioritize JupyterLab 3 if you think we're close
