### ISSUE TITLE
make strings localizable in jupyterlab-git extension

### ISSUE THREAD

**Issue by JessicaBarh** [StatCan/kubeflow-containers#227]
Jupyterlab-git is an essential extension for Jupyterlab but it is not OL-compliant

**Comment by JessicaBarh** [comment]
resolved in https://github.com/jupyterlab/jupyterlab-git/pull/888 
and by adding translation files to language pack in: https://github.com/StatCan/jupyterlab-language-pack-fr_FR/tree/main/jupyterlab_language_pack_fr_FR/extensions/jupyterlab-git

**Comment by ca-scribner** [comment]
working for me!

I haven't closed this in case there's other work that needs to be done.  Maybe add this to kubeflow-containers?  @JessicaBarh can you handle that (or close this if everything is set)?
