### ISSUE TITLE
Implement PSPP

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/kubeflow-containers#243]
Implement PSPP and create a working example showing how to access.
* PSPP is likely a desktop-only image, so only needs to be implemented in [remote-desktop](https://github.com/StatCan/kubeflow-containers/blob/b0260722f8754c40f7499af6b05e594aaab151ac/Makefile#L131)
* [Info on PSPP and installation (should be `apt install`)](https://www.gnu.org/software/pspp/get.html)
* Add a desktop shortcut

**Comment by jumana-s** [comment]
The remote-desktop build failed because the script to install PSPP included python as a package to install.  
Removing the python installation from the PSPP script fixed the build.
