### ISSUE TITLE
ml-workspace: Disable SSH access

### ISSUE THREAD

**Issue by frazs** [StatCan/kubeflow-containers#25]
To the extent of my experimentation, SSH (sshd and sslh through supervisor) could not be disabled on ml-workspace while still allowing connections through Kubeflow (only localhost/port-forward would work). I'm not fully sure what's going on under the hood here. This may be already covered by a security policy on another layer, but we need to make sure that external SSH connections (or at least the data leak avenues they can enable:  scp, sftp, rsync, sshfs...) cannot be made.

**Comment by frazs** [comment]
So far the only way I've been able to ssh in is inside the container, to the container's own internal IP only, with `sudo $(which sshd) -d -p 22` running in another terminal window. But I don't know if I've exhausted all variants. 

During today's standup, it was brought up that disabling external SSH in could be done as part of an Istio policy.

**Comment by justbert** [comment]
Or at least, if not fully mitigated, could be shored up with Istio networking policies.

**Comment by frazs** [comment]
As Brendan mentioned yesterday, when we get back to this we should also look into sslh. For now, this makes sense to put on hold pending other cleanup and fixes, particularly as sshd is presently mysteriously crashing out (which is well enough for not wanting external access, but should still be identified)
