### ISSUE TITLE
ml-workspace: image size reduction

### ISSUE THREAD

**Issue by frazs** [StatCan/kubeflow-containers#26]
Presently, changing ml-workspace from root to joyvan in the Dockerfile on a new layer blows up the image size (~8gb to ~14gb for cpu, ~17gb to ~30gb for gpu) due to file duplication caused by chmod and chown commands (the originals are kept on the preceding layers). I am considering two avenues to tackle this; there may be others:

**1. Rewrite the original ml-workspaces Dockerfile**. The main issue there is that I cannot get that to build: even when completely unchanged, it fails on step 50/97 while building either jupyterlab or one of its extensions, and I am having trouble even getting a log for that failure. I could try running the preceding step and building jupyterlab from the shell...

**2. Change permissions outside the build process**: Perhaps through an exec script.

Unsuccessful approaches included squashing and the devicemapper storage driver (although it may still be useful within a single layer).

**Comment by justbert** [comment]
Is the image build failing due to the tooling (Docker) or perhaps the resources of the machine on which it's built? Perhaps provisioning a beefier machine for the build of these images may help or trying a different tool. [Bazel](https://bazel.build/) tends to be in use in many places.

**Comment by frazs** [comment]
Thanks for showing me Bazel! I wasn't aware of it and it looks very nice.

I've tried the build on a D4s v3 (4 vcpus, 16 GiB memory) with failure at the same step, though I can try going beefier, seeing if Bazel makes a difference, and double-checking whether there are any resource limits being imposed on the docker daemon.

A similar sounding build issue has been [noted upstream](https://github.com/ml-tooling/ml-workspace/issues/28) and I tried building off the development branch (set up to send build logs to /dev/stdout), but unfortunately did not see any extra information (beyond `RuntimeError: JupyterLab failed to build`) during build.

I've also tried adding build-minimize=False [as noted here](https://github.com/jupyterlab/jupyterlab/issues/7180#issuecomment-529693228) but it would still fail during the extensions, which were still going through minimize. I'll see if there's a way to enforce that on the extensions as well, and if successful how the lack of minimize would impact the image size.

**Comment by frazs** [comment]
Haven't been able to figure out Bazel.

Identified the culprit in the build failure of the original Dockerfile: it is the jupyterlab Language Server Protocol extension @krassowski/jupyterlab-lsp. If I remove it, everything builds and seems to be working, but I'm not sure if we want to cut that feature.

What seems to be behind the issue is that in ML-Workspace, jupyterlab is fixed to version 1.2.6, and the latest version of @krassowski/jupyterlab-lsp no longer supports it (only jupyterlab 2). If I instead install @krassowski/jupyterlab-lsp@0.8.0, that goes through, but then VS Code fails. I'll see if I can find a way around that failure, but otherwise so far excising LSP has been the only success.

I've tried upgrading jupyerlab to the latest version inside the image, but a lot in the image depends on it being version 1. To get it to build at all, I had to install all other conda libraries through the conda-forge channel, get a different version of SpaCy, and disable the Plotly extension... but it still complains of multiple outdated extensions and ultimately fails to run with the equally morbid and uninformative "Child was dead when forwarding signal".

**Comment by blairdrummond** [comment]
That's awesome. Personally I think, since we already have a well-developed jupyterlab in the other image, ditching jupyterlab-lsp is totally acceptable for now. A much higher priority for me is focussing on the other apps like R-Studio (which you already got running).

I think you can proceed without lsp and then we can cycle back to it in the future if we need to.

**Comment by frazs** [comment]
While looking into a different error, I found a minimal solution that seems to preserve LSP and not generate any errors:

1. Change `@krassowski/jupyterlab-lsp` to `@krassowski/jupyterlab-lsp@0.8.0`
2. Change `pip install jupyterlab-git` to `pip install jupyterlab-git==0.9.0` (the trick here is that while the latest version of jupyterlab-git claims to be backwards compatible, some of the dependencies it brings along, notably nbdime, aren't!)

Let's call this version A.

I also realized that the version where I upgraded jupyterlab to 2.1.2 (and many other packages to their more up-to-date conda-forge version) actually runs too. I had accidentally specified the wrong port forward (we use 8888 on k8s; the default is 8080). The tini warning about the dead child process with the forwarded signal only seems to have happened the very first time I tried to launch it (and I didn't see it reappear with another attempt at the wrong port), so that mystery remains.

The main differences in that version are that the two jupyterlab Plotly extensions must be removed (they do not support jupyterlab 2 yet), and several other jupyterlab extensions warn that they are outdated, but I do not know if that means that they will not work or that they're simply obsolete (due to e.g. having their functionality incorporated into jupyterlab 2).

Let's call this version B.

Without any further changes yet applied (joyvan, any squashing/flattening tests, etc), A builds to 8.16GB, and B builds to 8.55 GB.

Tomorrow I'll work on incorporating the changes from #24 (joyvan user, optional QGis, pre-installed RStudio). Any preference on which version I should tackle: A which is closest to upstream, B which has more up-to-date packages but may be less stable, or go for both?

**Comment by blairdrummond** [comment]
In my view, the jupyter stuff can be treated as secondary in ml-workspaces, since the jupyter images are up-to-date and very polished. So I would say Stable > Up-to-date. I think it's totally your judgement past that point. But anything you need to rip out of Jupyter or deprecate, do it without remorse :-) 

If we get R-Studio rocking and keep the image size smallish, then I call that a huge win

**Comment by brendangadd** [comment]
@blairdrummond I agree that Jupyter in `ml-workspace` is secondary, and I'm going so far as to wonder if it should be there at all when I consider it alongside the other images.

I think it's worth us putting our heads together with @frazs and @chritter to decide precisely what tools are included and why.

**Comment by frazs** [comment]
I think there's definitely value to removing anything that is covered by other available images, when there is no benefit (such as particular GUI needs) to launching it inside of ml-workspace as opposed to alongside it (e.g. another image in another tab, perhaps connected to the same data sources). This will decrease not only the image size but also the workload for maintenance and dependency management. Plus it will reduce the risk of having a single point of failure for a multitude of tools.

**Comment by frazs** [comment]
I had the strangest issue after applying non-root user changes to the raw build. The GUI (xfce4) would refuse to load, with an "Unable to load a failsafe session" error, even when everything seemed to be set up identically (redundancy and all) to the working extended image.

I tracked down the issue to a mysteriously inaccessible .config folder. `ls -la` on root in either image, or joyvan (to-do: fix that typo) in the extended image, would return
```
drwxrwxrwx 1 joyvan joyvan 4096 May  6 23:30 .
drwsrwsrwx 1 joyvan joyvan 4096 May  6 23:30 ..
drwxrwxrwx 1 joyvan joyvan 4096 Apr 17 23:44 Code
drwxrwsrwx 1 joyvan joyvan 4096 May  6 23:30 configstore
drwxrwsrwx 1 joyvan joyvan 4096 May  6 23:26 git
drwxrwxrwx 1 joyvan joyvan 4096 Apr 17 23:44 gtk-3.0
drwxrwxrwx 1 joyvan joyvan 4096 May  6 23:30 matplotlib
-rwxrwxrwx 1 joyvan joyvan  103 Apr 17 23:44 mimeapps.list
drwxrwxrwx 1 joyvan joyvan 4096 Apr 17 23:44 xfce4
```
But `ls -la` on joyvan in the raw build would return:
```
ls: cannot access 'configstore': Permission denied
ls: cannot access 'git': Permission denied
ls: cannot access 'Code': Permission denied
ls: cannot access 'gtk-3.0': Permission denied
ls: cannot access 'xfce4': Permission denied
ls: cannot access 'matplotlib': Permission denied
total 12
drwxrwxrwx 1 joyvan joyvan 4096 May  6 23:30 .
drwsrwsrwx 1 joyvan joyvan 4096 May  6 23:30 ..
d????????? ? ?      ?         ?            ? Code
d????????? ? ?      ?         ?            ? configstore
d????????? ? ?      ?         ?            ? git
d????????? ? ?      ?         ?            ? gtk-3.0
d????????? ? ?      ?         ?            ? matplotlib
-rwxrwxrwx 1 joyvan joyvan  103 Apr 17 23:44 mimeapps.list
d????????? ? ?      ?         ?            ? xfce4
```
Which is wild given that these are full recursive rights on everything and the parent directory.

The only remaining difference I found between these two images, is that in the raw built image, .config is brought in as part of `COPY resources/home/ $HOME/` (and there are other folders coming in from this that *do not* experience this permissions issue, and adding a --chown joyvan:joyvan flag had no effect). Whereas in the extended image, this happened to /root during the build process of the default Dockerfile that was FROM'ed in, so it's brought in as part of `RUN cp -R /root/. /home/joyvan`.

...Which led me to the following "solution". This works! I still have no idea why:

```
RUN mv $HOME/.config $HOME/.config2 && \
    mv $HOME/.config2 $HOME/.config
```

😐

**Comment by brendangadd** [comment]
@frazs Really weird. Does doing a `chmod ugo+x` on one of the directories change anything for a subsequent `ls`?

**Comment by frazs** [comment]
Nope

**Comment by brendangadd** [comment]
These changes are now present in master of StatCan/kubeflow-desktop. Closing this issue as implemented.
