### ISSUE TITLE
Add man pages to containers

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-containers#274]
At the moment man pages are not available in the jupyter notebooks. We should fix that!

- [ ] Also, do a before/after comparison of the size

**Comment by Nancy-Badran** [comment]
On minimized Ubuntu systems, `man` is overriden by a script that output a warning message " This system has been minimized....".   So man is diverted to a different location `man.REAL`,  A workaround could be to remove that diversion.

**Comment by Nancy-Badran** [comment]
The size increased from 6.5 to 9 GB.
