### ISSUE TITLE
ml-workspace: non-root user

### ISSUE THREAD

**Issue by frazs** [StatCan/kubeflow-containers#28]
By default, ml-workspace images have everything hardcoded to /root and running as root. This issue tracks changing that, starting with refactoring to a non-root single user ('joyvan').

[Upstream issue](https://github.com/ml-tooling/ml-workspace/issues/11)

PR for initial attempt (cpu-only due to image size issues discussed in #26):  #24

**Comment by brendangadd** [comment]
Closing: this was merged into `non-root-manual-build` (not `master`).
