### ISSUE TITLE
Remote desktop nightly build failing

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-containers#284]
Looks like a QGIS key has changed

https://github.com/StatCan/kubeflow-containers/runs/3275310910?check_suite_focus=true#step:7:10032

@Jose-Matsuda can you tag Rohan or Salwa and take a look at updating the key?

**Comment by Jose-Matsuda** [comment]
Others have reported this issue see https://github.com/qgis/QGIS/issues/44612
