### ISSUE TITLE
request packages cansim and stats-can

### ISSUE THREAD

**Issue by chritter** [StatCan/kubeflow-containers#29]
Hello,
To access StatsCan data we will need the R package `cansim` (https://mountainmath.github.io/cansim/index.html)  and the Python package `stats-can` (https://github.com/ianepreston/stats_can) on all images.

**Comment by brendangadd** [comment]
@chritter Ideally we want to limit the individual packages we include in the containers so that we don't have to update the Docker images as often. Is there anything preventing users from installing these packages with `pip` etc.?

/cc @blairdrummond

**Comment by blairdrummond** [comment]
Yeah I think I agree. We can install these packages at runtime. @chritter we can just make example Notebooks where we're grabbing StatCan data using these packages.

**Comment by brendangadd** [comment]
Closing, as users can install referenced packages using standard tools. Example usage of these packages is added via StatCan/jupyter-notebooks#10.

**Comment by chritter** [comment]
@blairdrummond Thanks for adding the package installation code snippets.
