### ISSUE TITLE
ml-workspace: SQL databases

### ISSUE THREAD

**Issue by frazs** [StatCan/kubeflow-containers#30]
Do we need any? @chritter are you aware of any SQL database requirements for data science tools?

To-do for myself: confirm if any of the basic software depends on them (by default several are installed)

**Comment by brendangadd** [comment]
* I would like to avoid SQL servers like PostgreSQL and MySQL which will open ports on the container.
* If we do need to support relational data structures for analysis, then something like `sqlite` would be preferable.
* If we offer SQL capabilities directly, or if/when a need arises for external SQL data sources, we can add an aftermarket option for an SQL client (e.g. restoring DBeaver or similar software).

**Comment by frazs** [comment]
Removed in #34 to the extent that something else (e.g. QGis) doesn't add it back as needed.

**Comment by chritter** [comment]
@frazs Yes, PostgreSQL was under consideration for the Newsdata project but we decided to go with ElasticSearch. I expect DBs to be requirements in other projects. @brendangadd Would you consider helm chart deployments limited to the namespace a problem?

**Comment by brendangadd** [comment]
@chritter Helm deployments are possible, but should be something of a last resort for platform end-users. For analysis-oriented personas, data sources the likes of PostgreSQL should be consumed, not produced.

I'm not a data engineering expert by any stretch of the imagination, but I see PostgreSQL more as a transactional data store (e.g. backing some production application) than an analytical one – though it is indeed capable of fulfilling those types of needs. I would usher people towards alternatives:

* sqlite – would need some investigation on how big that can scale (e.g. distributed compute scenarios)
* Columnar storage (e.g. Parquet) + Pandas/Arrow data frames
* Querying the above using Minio's SQL-like API
* When data gets huge, using Spark's SQL features atop these data formats
* Data virtualization layer (when we have one)

Those scenarios can be expressed as artifacts atop our core analysis and data pipeline services. In cases where data engineering best practices would support the use of a server-style RDBMS, it would be shifted to the data provider/engineer persona and associated tools:

* Persistent data pipeline landing data in...
* Azure PostgreSQL DB (managed service)
* Management of above deployment to be determined

**Comment by blairdrummond** [comment]
@chritter You might be interested in the content of this PR

https://github.com/StatCan/jupyter-notebooks/pull/15

It gives a demo of executing SQL queries to data inside of object storage directly, and then loading it either as an Arrow Table or a Pandas Dataframe (on disk it's either `.csv`, `.csv.gz`, or `.parquet`). Eliminates a lot of the need for SQL if you can query your data this way just as a tabular data format. This is what @brendangadd mentioned above.

**Comment by chritter** [comment]
@blairdrummond Thanks for sharing.
