### ISSUE TITLE
Remove `--allow-root` ?

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-containers#31]
Um. I think we might not even need --allow-root in the kubeflow images. I removed it and launched the notebook just fine.

try out this image
<the registry>/kf-notebook-no-root

Or build it yourself

no-root-test.tar.gz

@brendangadd @sylus @ca-scribner

Any thoughts on what we'd need to test before removing things? Based on the notes in

kubeflow/kubeflow#300

it seems like they left --allow-root in so that uses could apt-get?

**Comment by brendangadd** [comment]
Yep, I had a read through the Kubeflow issue – let us give thanks they didn't go with inc0's approach – and it really doesn't look like the root user has anything to do with it.

It's mentioned that they `su jovyan` in the `start.sh`, but that would be at the image level rather that KF. And our images do `USER jovyan` with no `su` in the startup.

So this really does look to me like `--allow-root` – which is just a Jupyter-level flag – is completely unnecessary. I also considered that this flag would apply to what the terminal can do, but [the docs][] suggest to me that it has to do with the user who runs the notebook process. So I think we could still selectively elevate privilege as required via other means, the most trivial probably being granting some `sudo` to `jovyan` for the terminal.

[the docs]: https://jupyter-notebook.readthedocs.io/en/latest/config.html
