### ISSUE TITLE
Add R-Studio image for KF "notebook" servers

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-containers#32]
I've been experimenting with adding R-Studio to the images. It adds about 700mb (7.25gb -> 7.95gb), but it provides a really nice and responsive interface. It's honestly super nice for R. You can try it with

Custom Image: `<omitted>/kf-rstudio`

It gets even better if you switch from `lab` view to `rstudio` (I have only figured out how to do it by adjusting the url, or getting there from tree view).

Dockerfile below

```
FROM <omitted>/minimal-notebook-cpu:master
USER root

# install rstudio-server
ARG RSTUDIO_VERSION=1.1.463
ARG SHA256=62aafd46f79705ca5db9c629ce3b60bf708d81c06a6b86cc4b417fbaf30691c1
RUN apt-get update && \
    curl --silent -L --fail "https://download2.rstudio.org/rstudio-server-${RSTUDIO_VERSION}-amd64.deb" > /tmp/rstudio.deb && \
    echo "${SHA256} /tmp/rstudio.deb" | sha256sum -c - && \
    apt-get install --no-install-recommends -y /tmp/rstudio.deb && \
    rm /tmp/rstudio.deb && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
ENV PATH=$PATH:/usr/lib/rstudio-server/bin

RUN python3 -m pip install jupyter-rsession-proxy
RUN cd /tmp/ && git clone --depth 1 https://github.com/jupyterhub/jupyter-server-proxy && \
    cd jupyter-server-proxy/jupyterlab-server-proxy && \
    npm install && npm run build && jupyter labextension link . && \
    npm run build && jupyter lab build && \
    jupyter lab clean && \
  npm cache clean --force && \
  rm -rf /home/$NB_USER/.cache/yarn && \
  rm -rf /home/$NB_USER/.node-gyp && \
  fix-permissions $CONDA_DIR && \
  fix-permissions /home/$NB_USER


WORKDIR /home/$NB_USER
EXPOSE 8888
USER $NB_USER
ENTRYPOINT ["tini", "--"]
CMD ["start-custom.sh"]
```

I'm interested in figuring out the best way to incorporate this. In my opinion it offers a great experience for editing `R`.

Interested to figure out the best way to integrate this. If we made it a separate image, we could use `rstudio` view by default instead of lab view, and make it an R-Centric experience. On the otherhand, offering an A+ R-Experience in every image is kinda cool.

@sylus  @zachomedia

**Comment by brendangadd** [comment]
@blairdrummond From our discussion:
* Start with a separate image
* Can merge in the future if needed (easier than the other way around)
* UX is looking into this in the meantime
