### ISSUE TITLE
ml-workspace: Add GPU version of the image

### ISSUE THREAD

**Issue by frazs** [StatCan/kubeflow-containers#37]
Do we want a GPU version of ml-workspace, or are GPU processing needs sufficiently covered by other notebooks?

If we want a GPU version of ml-workspace, what software should we provide?

**Comment by chritter** [comment]
@frazs Yes, we do part of our deep learning modeling work in PyCharm or VS Code. So ml-workspace definitely needs a GPU version. Will check the software stack from the machine-learning-gpu image.

**Comment by frazs** [comment]
@chritter I would like to clarify:

Is VSCode alone sufficient, or should PyCharm to also be available?

Is VSCode and/or PyCharm the only thing you need in addition to what's available in the machine-learning-gpu image? Or do you also need other features of ml-workspace, particularly anything to do with the Desktop GUI?

**Comment by chritter** [comment]
@frazs VS Code is sufficient. Thank you!

**Comment by frazs** [comment]
@chritter I still need information on what kind of software you would want for the GPU processing itself. I think you mentioned CUDA, are there others? Also, which version of CUDA?

**Comment by chritter** [comment]
@frazs I would need the following version. 
```
torch         : 1.0.0
torch cuda    : 9.0.176 / is available
torch cudnn   : 7401 / is enabled
```
I have a image with this software stack you  could look at if you want.

**Comment by frazs** [comment]
@chritter Sure, where can I see the image?

**Comment by frazs** [comment]
As discussed in today's standup, let's use this issue to determine what to put in an official GPU image for general users.

For a starting point, here's what's included in the ml-workspace GPU flavour: https://github.com/ml-tooling/ml-workspace/blob/master/gpu-flavor/Dockerfile

Is there anything we should remove? Add?

**Comment by frazs** [comment]
Also, should the GPU image include RStudio and its supporting libraries? RStudio server? QGIS and the Geomatics libraries?

**Comment by chritter** [comment]
@frazs The  existing notebook server hosting RStudio are sufficient from my point of view.  I would say QGIS and other geomatrics libraries within my work scope can be easily operated from a non-GPU server. So, no need for these software stacks from my perspective.

**Comment by chritter** [comment]
This is done and @frazs did a great job to build our image.
