### ISSUE TITLE
ml-workspace: Refactor tools dropdown into splash page with buttons

### ISSUE THREAD

**Issue by frazs** [StatCan/kubeflow-containers#38]
Presently when connecting to ml-workspace the view is a jupyter notebook with various tools (such as a VNC connection to a GUI desktop) in the top right corner.

We want this refactored to a splash page with buttons (no jupyter notebook, options easier to access).

The current state is generated by a jupyter extension (open tooling), and front-end development is not my forte, so I will take an initial look and may even be able to wrangle the jquery (to be fully confirmed) into a basic solution, but may later need support on this.

What I would like to open up for immediate discussion is any feedback on what tools should be offered on the splash page and what should be accessed in the VNC environment.

An important note is that if Filebrowser is used to upload/download files into the image, it is my understanding that this will need to be a splash-page tool. Opening Filebrowser inside the VNC session uselessly connects to the file system of the image itself, though perhaps there is a workaround I haven't discovered.

**Comment by brendangadd** [comment]
Pulling back into general backlog just for sprint tracking because it over-commits time. @frazs This is still your go-to if you find yourself with a bit of extra time.

**Comment by frazs** [comment]
Should be possible and probably ideal to completely decouple the splash page from Jupyter, which could then be removed or downsized. Estimating XL due to minimal front-end experience & taking into account prior work.

**Comment by frazs** [comment]
Nginx routing threw a major wrench in the works. What was trivial to load on localhost is much more complicated on Kubeflow, where there is a custom workspace base URL to contend with. Julie and I are trying to work this out.

[The configuration](https://github.com/StatCan/kubeflow-containers-desktop/tree/master/base/resources/nginx) is complicated with a [large nginx.conf that uses Lua and OpenResty](https://github.com/StatCan/kubeflow-containers-desktop/blob/master/base/resources/nginx/nginx.conf), is further modified by a [Python script](https://github.com/StatCan/kubeflow-containers-desktop/blob/master/base/resources/scripts/configure_nginx.py), and involves [an sslh forward](https://github.com/StatCan/kubeflow-containers-desktop/blob/master/base/resources/supervisor/conf.d/sslh.conf). While trying to figure all this out I lost over a day of work before realizing that I was dealing with some cached redirects from prior code changes, which were of course not being cleared by a hard refresh (as that would happen after the redirect takes place).

Here's what I figured out so far:

- Whatever's in `location /` seems to affect other locations, which can result in infinite redirects and all sorts of other mess.
```
 location / {

            # proxy_pass http://jupyter;
            root /resources/;
            ...
```
- The above will work on localhost, but on Kubeflow will attempt to route the workspace base URL, e.g. looking for a nonexistant _/resources/notebook/frances-zsurka/splashtest31/index.html_ .
```
location = "{WORKSPACE_BASE_URL_DECODED}/julie"
        {
            types { } default_type "text/html";
            alias /resources/index.html;     
        }
```
- The above will... sort of work, on localhost and on Kubeflow. Unlike when using `/root/resources`, the line `types { } default_type "text/html";` must be included for the page to load as HTML and not as plain text, even though the HTML file contains `<meta http-equiv="Content-Type" content="text/html">` (with or without further encoding tags). Adding a `mime.types` file and adding `include /etc/nginx/mime.types;` to `nginx.conf`, either in the general http block and/or in this location block, does not make a difference.

There are three issues:

1. Relative links do not work properly. A link to `/tools/vscode` should go to, for instance, `https://kubeflow.covid.cloud.statcan.ca/notebook/frances-zsurka/splashtest32/tools/vscode/`, but instead it goes to `https://kubeflow.covid.cloud.statcan.ca/tools/vscode`. I'm not actually sure whether this is a symptom of some routing issue or something I'd need to handle on the front-end to begin with, but either way I could work around this with javascript, e.g. by grabbing `window.location.href` and adding that to the relative link to build the appropriate URL.
2. The splash page should be the landing page, so if there isn't a way to make it show up at `https://kubeflow.covid.cloud.statcan.ca/notebook/[namespace]/[container_name]/` through Nginx, we need to find a way to make it so that when the container is connected to, it goes right to an appropriate subdirectory (`/splash`?). Is there a way to do this through some sort of e.g. Kubeflow configuration?
3. Filebrowser now complains `Please provide a valid API token via token get parameter` instead of loading. Not sure yet what breaks and how.

In regards to tackling 2 through nginx...

```
        location / {

            #proxy_pass http://jupyter;
            return 302 "{WORKSPACE_BASE_URL_DECODED}/julie/"; 
```
- The above makes an infinite redirect, as the `return 302` also runs at `{WORKSPACE_BASE_URL_DECODED}/julie/` despite not being in that location block.

```
 location = "{WORKSPACE_BASE_URL_DECODED}"
        {
            types { } default_type "text/html";
            alias /resources/index.html;     
        }
```
- This seems to get ignored. If `location /` is commented out, there's just a `Welcome to OpenResty!` page.

```
(With "location /" commented out)
 location =/
        {
            types { } default_type "text/html";
            alias /resources/index.html;     
        }
```
- `"/resources/index.htmlindex.html" is not a directory`

```
(With "location /" commented out)
 location =/
        {
            types { } default_type "text/html";
            alias /resources/;     
        }
```
-`Welcome to OpenResty!`

```
(With "location /" commented out)
 location =/
        {
            return 302 "{WORKSPACE_BASE_URL_DECODED}/julie/";
        }
```
-`"/usr/local/openresty/nginx/html/julie/index.html" is not found` How are you in there now?! Same result for `http://$host{WORKSPACE_BASE_URL_DECODED}/julie/` and `$uri/julie;`.

```
(With "location /" changed to "location = /")

    location = / {

            # proxy_pass http://jupyter;
            proxy_pass http://127.0.0.1:8092{WORKSPACE_BASE_URL_ENCODED}/julie;

            proxy_set_header X-Real-IP $remote_addr;
            # Todo: change to http_host? host does not include the port (= higher security?)
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Origin ""; # set origin to empty, otherwise Jupyter returns a bad origin request
        
            # websocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
```
- This works on localhost, but Filebrowser still complains `Please provide a valid API token via token get parameter.` instead of loading, and on Kubeflow I get `"usr/local/openresty/nginx/html/notebook/frances-zsurka/quicktest7/index.html" is not found`. Same behavior with `WORKSPACE_BASE_URL_DECODED`.


...Anyway, I'm stumped. This is my first time using Nginx, and my limited prior experience with Apache has been simple and well-behaved out of the box, so I have a feeling I'm butchering or misunderstanding something.

**Comment by frazs** [comment]
I forgot to mention, but in case it's relevant to any debugging, with no other changes to nginx.conf and the creation of a `/resources/julie/index.html`, adding the following block:
```
location = /julie {
            auth_basic off;
            root /resources/;
            index index.html;  
        }
```
...And attempting to access `/julie` results in an infinite redirect between `/julie` and `/julie/`.

I have tried commenting out the following code with no impact:
```
  # if base path is not in request url -> alway redirect to base path
        location ~* "^(?!{WORKSPACE_BASE_URL_DECODED}).*$" {
            auth_basic off;
            return 302 {WORKSPACE_BASE_URL_ENCODED}$request_uri;
        }
```

**Comment by frazs** [comment]
To make things wildly more confusing, I am now actually getting the `Please provide a valid API token via token get parameter.` Filebrowser error everywhere, including old images (local and Kubeflow) that have nothing to do with this splashpage work and that were previously working :confused:

**Comment by frazs** [comment]
Alright, disregard all the `Filebrowser` comments, that was a separate issue and is resolved on my end. The major issue remaining here as far as routing is concerned is how to get the splash page to be the landing page.

**Comment by frazs** [comment]
Routing is resolved. Here's the crux of the issue:
```
        location = "{WORKSPACE_BASE_URL_DECODED}"
        {
            types { } default_type "text/html";
            alias /resources/index.html;     
        }
```
Let's say my `WORKSPACE_BASE_URL` is `/notebook/frances-zsurka/test`.
The above would work on localhost, e.g. `http://localhost:8888/notebook/frances-zsurka/test`. We found this out once I found the right place to put in a placeholder `WORKSPACE_BASE_URL` (inside [init.sh](https://github.com/StatCan/kubeflow-containers-desktop/blob/master/base/init.sh)) as otherwise `WORKSPACE_BASE_URL` is equal to `NB_PREFIX`, which is empty on localhost. 

However, Kubeflow expects a `/` at the end (e.g. `https://kubeflow.covid.cloud.statcan.ca/notebook/frances-zsurka/test/`), and removing the final `/` will result in an invalid page error from the Kubeflow GUI. But this `location` is only a match for a `WORKSPACE_BASE_URL` without a `/` at the end.

So then what about `location = "{WORKSPACE_BASE_URL_DECODED}/"`?

Well, for some reason, that would make Nginx try to access `/resources/index.htmlindex.html`, and then complain that it is not a valid directory.

So, since it's appending an extra index.html for some reason, why not try to account for that?:

```
        location = "{WORKSPACE_BASE_URL_DECODED}/"
        {
            types { } default_type "text/html";
            alias /resources/;     
        }
```

No dice, that location block got ignored!

I tried a few different permutations, e.g. declaring `index index.html` was no help... **But for some reason, this specifically works:**

```
        location = "{WORKSPACE_BASE_URL_DECODED}/"
        {
            types { } default_type "text/html";
            alias /resources/;
            try_files /index.html =404;  
        }
```

I'm still trying to comprehend exactly what's going on, particularly since for a subdirectory (e.g. ` location = "{WORKSPACE_BASE_URL_DECODED}/splash"` a straightforward `alias /resources/index.html;` alongside the type definition is sufficient. 

But the splash page that now (finally!) loads on Kubeflow still needs to be finished (at least to a basic extent to be perhaps later spruced up by a front-end designer in the future). Hopefully separating out CSS and JavaScript won't cause further routing problems, but in the worst case going all-in-one for a generally simple 5-button splash page might not end up too egregious, at least for a tentative working solution. And there are still a couple of places where I want to confirm that jupyter can be safely decoupled. So I'm moving on to such other components of this issue for now.

**Comment by chritter** [comment]
@frazs It would be great to add the Jupyter Lab support back to the image, as I found its capabilities also relevant for my analysis with ml-workspace. I have not used the Filebrowser at all as I use the VS Code browser. Its capability to share data through permanent links seems interesting.

**Comment by frazs** [comment]
I believe the file sharing through links in Filebrowser will only be available to your workspace contributors, which is good from a security standpoint. Sharing through Minio would have more capabilities.

Decoupling jupyter from the landing page should still leave it usable, and if we restore JupyterLab (to be discussed) or want an option for the original jupyter tree UI, either or both could be added as a button on the splash page.

**Comment by frazs** [comment]
Once the landing page image is built and confirmed working, if there are no further developments to propose, I'll mark the PR for adding it to the manifest as resolving this issue. 

One change I can think of is removing the Jupyter button once sharing storage across multiple images is supported, but I think that makes the most sense as part of a separate future "remove Jupyter" issue.
