### ISSUE TITLE
Improve image inheritance strategy

### ISSUE THREAD

**Issue by brendangadd** [StatCan/kubeflow-containers#48]
We want to benefit as much as possible from upstream fixes in Jupyter's core docker stacks, but also be able to inherit from our own base image so we can fix our own layers in a minimal number of locations. Right now, our base image inherits from deep in the core docker stack tree.

I'm wondering if we should use a mixin approach so we can benefit from upstream fixes to the whole tree without pushing our base image to a leaf node. This will allow us to extend from multiple locations in the core tree while preserving common config of our own.

**Comment by sylus** [comment]
I think this issue was closed with the recent merge?

Feel free to re-open but this looks solved to me.
