### ISSUE TITLE
ml-workspace VS Code Docker extension

### ISSUE THREAD

**Issue by chritter** [StatCan/kubeflow-containers#52]
Hello,
The rich docker extension for VS Code does not work on the ML-Workspace image due to the VSCode version. This extension is very convenient for docker development. Thanks!

![image](https://user-images.githubusercontent.com/15911039/83303012-5634fb80-a1ca-11ea-8d9c-10272bd2403d.png)

**Comment by blairdrummond** [comment]
@chritter I think docker cannot be run securely. You might have an older image where you can launch as root, but that's not supposed to be allowed going forward...

Correct me if I'm wrong @brendangadd

**Comment by frazs** [comment]
Is this issue closed for now, or would you like a VS Code update for any other reasons? We would have to confirm that it wouldn't break any existing extensions in use.

**Comment by chritter** [comment]
@frazs If docker is not supported then the extension is not needed. The issue can be closed. thanks.
