### ISSUE TITLE
ml-workspace: allow change of keyboard layout

### ISSUE THREAD

**Issue by chritter** [StatCan/kubeflow-containers#57]
Hello,
I work with a Mac which has a different keyboard layout than those available in the VNC session of the ml-workspace. It would be great to have an option to change the keyboard layout.

**Comment by frazs** [comment]
This one would be tricky for me as I do not have a mac keyboard to test

**Comment by chritter** [comment]
@frazs I would be happy to assist with the testing. I am working now heavily in the workspace with geomatics tools and this would easy the usage.

**Comment by frazs** [comment]
On the image as-is, have you tried:

Applications (top left corner) -> Settings -> Keyboard -> 'Layout' tab

Uncheck 'System defaults' and select something that looks right, maybe `MacBook/MacBook Pro` or `MacBook/MacBook Pro (intl.)`?

Then, under 'Change layout option', I think that's what you want mapped to your Command key, and I'm not positive on where yours are, but try `Right Alt`, `Left Alt`, or just `Alt`

Mac keyboards don't typically feature a [compose key](https://en.wikipedia.org/wiki/Compose_key) so you can probably leave that blank.

**Comment by chritter** [comment]
@frazs I tried the Macbook layouts however `command` + `c` and `command` + `v` corresponding to copy and paste do not work. I tried the 'Change layout option'. Then I looked into `xmodmap` and tried to switch `control` and `command` keys. No success.

**Comment by chritter** [comment]
I am closing this one as I do not have the time to continue working on this.

**Comment by frazs** [comment]
I'd like for this to remain open as long as it is unresolved. Perhaps you or another Mac user will have some time available in the future, or I'll get access to a Mac keyboard or the means to simulate one.
