### ISSUE TITLE
Jupyterhub cross origin requests

### ISSUE THREAD

**Issue by asolis** [StatCan/kubeflow-containers#59]
Problem:
I am making a javascript request from a local web page (i.e., index.html inside a Jupyter lab session) to a running service on port 8001 on the same session by using the proxy/$port 
url path, e.g., https://kubeflow.covid.cloud.statcan.ca/notebook/andres-solismontero/test1/proxy/8001/. 

The service in question is an Uvicorn ASGI server app  running on port 8001. 

The javascript code inside the web page makes a GET request as follow

```
var url  = `https://kubeflow.covid.cloud.statcan.ca/notebook/andres-solismontero/test1/proxy/8001/hubs/HR_V.json`;

$.get(url, options, function(json){ ... }
```
Although is possible to access the ***url*** directly without problem, the web page is executed inside the notebook server html renderer and  the code is aborted by giving the following set of errors: 
```
[Error] Cross-origin redirection to https://login.microsoftonline.com/258f1f99-ee3d-42c7-bfc5-7af1b2343e02/oauth2/v2.0/authorize?client_id=de35dedf-3daa-4456-ae47-3bbc4169dd7a&prompt=select_account&redirect_uri=https%3A%2F%2Fkubeflow.covid.cloud.statcan.ca%2Flogin%2Foidc&response_type=code&scope=profile+email+openid&state=MTU5MTg4NTQ5MnxFd3dBRUhOMU5YbzNXVk5OZGpWT2VqVmhaalk9fJArvxG9ks_YUYBUQR60BUci9sKMxoj0VNSlrhvAmbQd denied by Cross-Origin Resource Sharing policy: Origin null is not allowed by Access-Control-Allow-Origin.
[Error] XMLHttpRequest cannot load https://kubeflow.covid.cloud.statcan.ca/notebook/andres-solismontero/test1/proxy/8001/hubs/HR_V.json?_shape=array&_json=geometry&_size=max due to access control checks.
[Error] Failed to load resource: Cross-origin redirection to https://login.microsoftonline.com/258f1f99-ee3d-42c7-bfc5-7af1b2343e02/oauth2/v2.0/authorize?client_id=de35dedf-3daa-4456-ae47-3bbc4169dd7a&prompt=select_account&redirect_uri=https%3A%2F%2Fkubeflow.covid.cloud.statcan.ca%2Flogin%2Foidc&response_type=code&scope=profile+email+openid&state=MTU5MTg4NTQ5MnxFd3dBRUhOMU5YbzNXVk5OZGpWT2VqVmhaalk9fJArvxG9ks_YUYBUQR60BUci9sKMxoj0VNSlrhvAmbQd denied by Cross-Origin Resource Sharing policy: Origin null is not allowed by Access-Control-Allow-Origin. (HR_V.json, line 0)
```

CC: @blairdrummond

**Comment by brendangadd** [comment]
@asolis Your request to `kubeflow.covid...` is sent out to the internet and routed back into the platform without context, so your app is being asked to authenticate – you'll notice that access is being denied to `login.microsoftonline.com`.

If you want that sort of thing to work, you'll probably have to set an appropriate Authorization header on your HTTP request.

**Comment by blairdrummond** [comment]
I think we also tried using localhost but without any luck. Can you remind me what the error was @asolis  ?

@brendangadd for reference; he has an html page with an iframe which is trying to access data on a local port, but we were getting errors that *i think* are related to this

https://github.com/jupyterhub/jupyterhub/pull/1539

Those errors were there when the html page still used a localhost address. I think *either* the Authorization header or that Jupyter fix should be a solution though? :crossed_fingers:

**Comment by asolis** [comment]
These are the errors while using localhost. @blairdrummond 

[Error] Blocked script execution in 'blob:https://kubeflow.covid.cloud.statcan.ca/2d843aaf-933a-46b0-837b-a6e8ab3f6a7f' because the document's frame is sandboxed and the 'allow-scripts' permission is not set. (x3)
[Error] Not allowed to request resource
	send (jquery-3.5.0.js:10099)
	ajax (jquery-3.5.0.js:9682)
	display_layer
	(anonymous function)
	dispatch (jquery-3.5.0.js:5429)
	trigger (jquery-3.5.0.js:8715)
	(anonymous function) (jquery-3.5.0.js:8793)
	each (jquery-3.5.0.js:381)
	Global Code
[Error] XMLHttpRequest cannot load http://localhost:8001/hubs/HR_V.json?_shape=array&_json=geometry&_size=max due to access control checks.
	send (jquery-3.5.0.js:10099)
	ajax (jquery-3.5.0.js:9682)
	display_layer
	(anonymous function)
	dispatch (jquery-3.5.0.js:5429)
	trigger (jquery-3.5.0.js:8715)
	(anonymous function) (jquery-3.5.0.js:8793)
	each (jquery-3.5.0.js:381)
	Global Code

**Comment by sylus** [comment]
@zachomedia ^

**Comment by blairdrummond** [comment]
@asolis Can you provide some notes on how to reproduce? The datasette command and the index.html page, plus the name of the pod where this is running? (We might jump in to test it)

**Comment by asolis** [comment]
1. Connect to Network Server **hubs** inside namespace **andres-solismontero** 
2. Navigate to the **shared-hubs/andres/** volume folder 
    ```
    $cd shared-bus/andres 
     ```
3. The database service is currently running, it should be possible to check if it's running using this url. 
    [https://kubeflow.covid.cloud.statcan.ca/notebook/andres-solismontero/hubs/proxy/8001](https://kubeflow.covid.cloud.statcan.ca/notebook/andres-solismontero/hubs/proxy/8001). In case it's stopped. Run the following command inside the **shared-hubs/andres** folder
    ```
     /shared-hubs/andres$ ./start_datasette.sh
```
4. Open `index.html` (it's currently trying to connect to localhost:8001) the connect url could be accessed in line 110 of the file (Feel free to update the link for testing). 
Note: make sure to hit TrustHtml when opening the index.html for it to run. 

content of index.html 
```
...
var url  = `http://localhost:8001/hubs/HR_V.json`;
...
```

The page should always show a world map centred in North-America. It only displays an interactive map with boundaries plus legend if it's successfully connected.

**Comment by asolis** [comment]
@zachomedia @blairdrummond 
I tried add a header request by adding  'kubeflow-userid', it seems to remove the Microsoft log-in error message. 
Bellow the code used:

``` javascript

		var url  = `https://kubeflow.covid.cloud.statcan.ca/notebook/andres-solismontero/hubs/proxy/8001/hubs/HR_V.json`;
		
		var options = {
			"_shape":"array",
			"_json" :"geometry",
			"_size" : "max",
                        "PRUID":"24"
		}

		
		$.ajax({
                            url: url,
                            data: options,
                            type: "GET",
                            dataType:'json',
                            beforeSend: function(xhr){xhr.setRequestHeader('kubeflow-userid',       'andres.solismontero@cloud.statcan.ca');},
                            success: function(json) { console.log(json); }
                });
```


These are the errors :


[Error] Blocked script execution in 'blob:https://kubeflow.covid.cloud.statcan.ca/7e27210a-09fb-4660-bb6f-fa9220d98289' because the document's frame is sandboxed and the 'allow-scripts' permission is not set. (x3)
[Error] Preflight response is not successful
[Error] XMLHttpRequest cannot load https://kubeflow.covid.cloud.statcan.ca/notebook/andres-solismontero/hubs/proxy/8001/hubs/HR_V.json?_shape=array&_json=geometry&_size=max due to access control checks.
[Error] Failed to load resource: Preflight response is not successful (HR_V.json, line 0)






If I change the url to localhost using the previous code (`http://localhost:8001/hubs/HR_V.json`), the errors are:

[Error] Not allowed to request resource
	send (jquery-3.5.0.js:10099)
	ajax (jquery-3.5.0.js:9682)
	display_layer (46dd441a-7707-45da-94f5-885838128061:119)
	(anonymous function) (46dd441a-7707-45da-94f5-885838128061:287)
	dispatch (jquery-3.5.0.js:5429)
	trigger (jquery-3.5.0.js:8715)
	(anonymous function) (jquery-3.5.0.js:8793)
	each (jquery-3.5.0.js:381)
	Global Code (46dd441a-7707-45da-94f5-885838128061:294)
[Error] XMLHttpRequest cannot load http://localhost:8001/hubs/HR_V.json?_shape=array&_json=geometry&_size=max due to access control checks.
	send (jquery-3.5.0.js:10099)
	ajax (jquery-3.5.0.js:9682)
	display_layer (46dd441a-7707-45da-94f5-885838128061:119)
	(anonymous function) (46dd441a-7707-45da-94f5-885838128061:287)
	dispatch (jquery-3.5.0.js:5429)
	trigger (jquery-3.5.0.js:8715)
	(anonymous function) (jquery-3.5.0.js:8793)
	each (jquery-3.5.0.js:381)
	Global Code (46dd441a-7707-45da-94f5-885838128061:294)

**Comment by zachomedia** [comment]
There are a lot of security features that will prevent this type of behaviour from happening for good reasons, otherwise the entire platform becomes vulnerable to basic web attacks.

Can I get a clear definition of the use case that's being tried here as we might need to identify a different solution for this.

Thanks

**Comment by asolis** [comment]
@zachomedia  It's basically a dynamic web page (html/javascript) that's connecting to a ASGI wrapper of  a database, to display/plot information. You can see it as a dashboard. I have no control over the ASGI implementation  and would like not to implement another variant of it. It does allow me to Allow-Origin:* while running and this flag is set to ON in the running script . The Datasette software used is a two fold ASGI/WSGI, it acts as a read only database management software WSGI  and a ASGI server returning json data.  

I understand that putting Access-Control-Allow-Origin:* might bring some concerns. But I was wondering if there's an intermediate way to connect to the server while restricting the origin. 

I mean, we already have access to the https://kubeflow.covid.cloud.statcan.ca/notebook/andres-solismontero/hubs/proxy/8001/hubs/HR_V.json with authentication.

**Comment by blairdrummond** [comment]
@zachomedia  He's serving up a sqlite database as a webservice within his kubeflow notebook with a tool called datasette, it's running on localhost:8001. Then he has a single index.html webpage with an iframe that renders some of that database info into a map with some javascript. They play with the database, and use the webpage as a dashboard. It all runs in a kubeflow notebook.

**Comment by blairdrummond** [comment]
@asolis ; can you get the webpage to read directly from the local db instead of via the webservice?

**Comment by asolis** [comment]
@blairdrummond The problem is I can't access any resource from index.html. I can't even't link a js file hosted in the same folder.  I just created this link and inside is trying to read a js file in the same folder. I get an Allow-Origin access problem. [https://kubeflow.covid.cloud.statcan.ca/notebook/andres-solismontero/hubs/files/shared-hubs/andres/index2.html?_xsrf=2%7C99bf0f50%7Cf620898a5d116e7601effc1b0b33e4ed%7C1591381666](https://kubeflow.covid.cloud.statcan.ca/notebook/andres-solismontero/hubs/files/shared-hubs/andres/index2.html?_xsrf=2%7C99bf0f50%7Cf620898a5d116e7601effc1b0b33e4ed%7C1591381666)

**Comment by asolis** [comment]
@zachomedia @blairdrummond  I fixed the problem by creating a WSGI (FLASK app) doing as a proxy between the client and datasette ASGI. Thanks!
