### ISSUE TITLE
Add container for LibPostal

### ISSUE THREAD

**Issue by JosephKuchar** [StatCan/kubeflow-containers#63]
Hi,

My group works with address data lot, and the address parser LibPostal and it's Python bindings PyPostal are used frequently. Would it be possible to set up a container (maybe based off of the geomatics container) with libpostal and pypostal installed?
https://github.com/openvenues/libpostal
https://github.com/openvenues/pypostal
Thanks,
Joseph

**Comment by blairdrummond** [comment]
The necessary tools to build the C-Library from source will probably also work. A scalable option might be the necessary build tools to make the program. (Might not solve every case)

CC @brendangadd

**Comment by blairdrummond** [comment]
Hey @JosephKuchar ; our Sprint cycle renews on Wednesday. I'll try to get this into planning.

**Comment by brendangadd** [comment]
I was wondering if this was a simple as adding the missing build requirement of `pkg-config` and `pip` would conveniently build the C libraries for you on installation. Not so. PyPostal seems to expect the library to already be present.

Installation instructions:
```sh
git clone https://github.com/openvenues/libpostal
cd libpostal
./bootstrap.sh
./configure --datadir=[...some dir with a few GB of space...]
make -j4
sudo make install

# On Linux it's probably a good idea to run
sudo ldconfig
```

In terms of providing that library, there are competing issues here at face value:

* The `sudo` requirement for some of those commands
* Keeping image sizes reasonable – "... some dir with a few GB of space..." is ominous
* Keeping number of images minimal

If we really need to use `sudo` to make this library available, then it needs to be in the Docker build. But how many of these GBs does `--datadir` require – and is my assumption correct that these need to hang around post-installation?

**Comment by blairdrummond** [comment]
My *hope* is that there might be a way to install these kinds of C libraries into /opt in a way that doesn't require root access, but then we'll probably need a way to get the C linkers to check there for the libraries (I am not a C programmer, lol)

Is a reasonable solution to split this into two tasks

1. Check how big libpostal is. If small, just install it in the geo image.
2. Figure out if we can get C libraries *like* libpostal compiled, linked, and cooperating with pip, without sudo.

**Comment by ca-scribner** [comment]
I second breaking it into two issues.  Let's tackle (1) here.

I also think Francis is the best to tackle this

**Comment by ca-scribner** [comment]
@JosephKuchar can you clarify something for us?  Would the ideal solution for you be a notebook server image that has this installed, so you could open a notebook server, open up jupyter or whatever, and then just `import pypostal; do_fun_stuff_with_pypostal`?  Just making sure we understand

**Comment by JosephKuchar** [comment]
> @JosephKuchar can you clarify something for us? Would the ideal solution for you be a notebook server image that has this installed, so you could open a notebook server, open up jupyter or whatever, and then just `import pypostal; do_fun_stuff_with_pypostal`? Just making sure we understand

Yes, that's pretty much what we're after. It's an optional dependency for another package created by a member of our team, [OpenTabulate](https://pypi.org/project/opentabulate/).

libpostal uses machine learning to do address parsing, so the few GB required for the data directory is for the training data. I don't believe it can be removed after installation, but it isn't something I've tried. I do have it installed on another machine, if it's helpful I can test it out.

**Comment by frazs** [comment]
Just tested this on one of my remote desktop images. There don't seem to be any issues with installing as root in a Dockerfile and accessing as a regular user in the container. It adds about 2.4GB of image size. Maybe a skosh less with `--no-cache-dir`, I forgot to add that. Here's what you want (while `USER root`):

```
RUN apt-get update && \
    apt-get install curl autoconf automake libtool python-dev pkg-config && \
    git clone https://github.com/openvenues/libpostal && \
    cd libpostal && \
    ./bootstrap.sh && \
    ./configure --datadir=/home/jovyan/libpostaldata && \
    make -j4 && \
    make install && \
    ldconfig && \
    pip install --no-cache-dir postal && \
    [the usual code for cleaning your docker image layer]
```

**Comment by frazs** [comment]
I'd also lean towards offering this in an image or as an image variant, as it is a fairly install process with a lot of complaints as is without going for a non-sudo route.

**Comment by ca-scribner** [comment]
@brendangadd @blairdrummond thoughts?  Just offer this as its own notebook image for now?

**Comment by blairdrummond** [comment]
I think it's fair to add it to geomatics, maybe?

**Comment by ca-scribner** [comment]
Ok I'm taking 17 hours of no objections as consensus :)  

@frazs can you add these tools to the current geomatics image please?

**Comment by frazs** [comment]
`conda install postal` in a terminal as a regular user inside a geomatics-notebook container works, and pulls in `libpostal` as well. In a python console, I was able to successfully run `from postal.parser import parse_address` followed by `parse_address('781 Franklin Ave Crown Heights Brooklyn NYC NY 11216 USA')`. 

Running the automated `nose` tests described in the [pypostal repo](https://github.com/openvenues/pypostal) originally couldn't find libpostal, but that was because its setup file had the Extension settings `include_dirs=['/usr/local/include']` and `library_dirs=['/usr/local/lib']`. Once these were updated to `/opt/conda/include` and `/opt/conda/lib` respectively they went through.

I threw in the PR above in case it is determined that these libraries make sense as part of the generic geomatics-notebook offering, but otherwise this would be possible to get going in your team's containers now.

**Comment by ca-scribner** [comment]
oh wow, good catch @frazs .  You'd think they'd have said something about conda on their install instructions!

**Comment by blairdrummond** [comment]
I am routinely shocked by what Conda can do.

**Comment by JosephKuchar** [comment]
Amazing - thanks all! I had no idea it had been integrated into conda. That definitely simplifies things!
