### ISSUE TITLE
remote-desktop: Address failed checksum on Netdata

### ISSUE THREAD

**Issue by frazs** [StatCan/kubeflow-containers#78]
I saw that the latest [automatic build failed due to a failed checksum for Netdata](https://github.com/StatCan/kubeflow-containers-desktop/runs/895985048?check_suite_focus=true). There have been [important recent security updates to Netdata](https://github.com/netdata/netdata/releases) and the simplest solution might be updating the [checksum](https://github.com/StatCan/kubeflow-containers-desktop/blob/master/base/resources/tools/netdata.sh#L6) corresponding to `wget https://my-netdata.io/kickstart.sh`. Still, this should be tested, and perhaps a more version-specific approach would be better.

**Comment by frazs** [comment]
This is the file that would need to be updated: https://github.com/StatCan/kubeflow-containers-desktop/blob/master/base/resources/tools/netdata.sh

Let's replace the installation script with a deb so that we know what version we're on and don't get messed up by surprise updates. For reference, here's something that installs a deb, note the use of the version variable: https://github.com/StatCan/kubeflow-containers-desktop/blob/master/base/resources/tools/vs-code-desktop.sh

And here's a deb for Netdata, we'll want the Ubuntu Bionic one netdata_1.23.2_amd64.deb over at https://packagecloud.io/netdata/netdata?page=4

We will need the sha256 for it, which can be obtained by downloading the deb yourself and running `sha256sum netdata_1.23.2_amd64.deb`: you may need to look up how to do this on MacOS

And then it's just a matter of making sure the remote-desktop-base image builds and runs (build can take a long time for the first time)

Let me know any questions :smile:

**Comment by saffaalvi** [comment]
Completed all steps mentioned above to resolve this issue. Updated netdata.sh to install `netdata_1.23.2_amd64.deb` as well as removed line 671 in the `base` Dockerfile and deleted the `base/resources/netdata` folder so the appropriate configuration for the Netdata version will be applied. 
Issue corrected in https://github.com/StatCan/kubeflow-containers-desktop/commit/1bb53bcaee586b9fc01c484066ab188ade2b498d
