### ISSUE TITLE
remote-desktop: Remove unnecessary VS Code extensions

### ISSUE THREAD

**Issue by frazs** [StatCan/kubeflow-containers#80]
[The ESLint and MarkdownLint extensions for VSCode](https://github.com/StatCan/kubeflow-containers-desktop/blob/master/base/Dockerfile#L582-L594) that are presently in the image are occasionally down, which causes the build to fail at that step. We should find a more reliable source for them. If one is not easily available, we could consider just adding the `.vsix` files to the image (perhaps in `/resources/tools`) and installing them from there, as they are quite small (<150 kb each).

**Comment by brendangadd** [comment]
VS Code installs extensions (all available via UI) to the user's home directory. That means:
* Users can do this themselves
* Installations will be preserved by the workspace volume

## Todo
* Remove the following VS Code extensions:
  * Code runner
  * eslint
  * markdownlint
* Ensure remaining extensions are up-to-date

/cc @saffaalvi @frazs
