### ISSUE TITLE
jupyterlab git extension build

### ISSUE THREAD

**Issue by saffaalvi** [StatCan/kubeflow-containers#84]
When a new `minimal-notebook-cpu` server is created and ran, an issue pops up right away:

<img width="969" alt="gt" src="https://user-images.githubusercontent.com/57377830/89337852-a9637880-d669-11ea-9c4d-0344126e1ce9.png">

Even after the "build" option is selected, jupyterlab doesn't let you do anything when you select "New Launcher", the page just remains blank.

Tried this with `minimal-notebook-gpu` as well and it has the same problem.

When I try to go into Extension manager and updating @jupyterlab/git extension, the following appears:
<img width="1241" alt="install" src="https://user-images.githubusercontent.com/57377830/89347455-d23f3a00-d678-11ea-8d4b-a05d09fa06ad.png">

**Comment by sylus** [comment]
I am not sure what would have caused this, maybe a bad CI build? 

Or could be we should have pinned jupyterlab-git and this was a regression?

https://github.com/StatCan/kubeflow-containers/blob/master/minimal-notebook/cpu/Dockerfile#L54

**Comment by sylus** [comment]
I did a commit to master since this was irreparably broken and I was pretty sure was elyra not doing well with the latest jupyterlab >= 2.1.1+.

Things seem to be working now and can look at maybe having Elyra and Kale done separately until stabilize.

**Comment by sylus** [comment]
https://github.com/StatCan/kubeflow-containers/commit/e2bfdd91ea1cf66c1a27613829214c4f763e8fa8

**Comment by sylus** [comment]
I think this can be closed now.
