### ISSUE TITLE
jupyterlab-git server extension loading failure

### ISSUE THREAD

**Issue by saffaalvi** [StatCan/kubeflow-containers#93]
When trying to create a notebook server with the custom image `k8scc01covidacr.azurecr.io/minimal-notebook-cpu:cb2d3bc0caacb89d36c2615dabd33fba6e875511` (latest commit in master) this error appears:

![image](https://user-images.githubusercontent.com/57377830/89835346-9bfb3200-db32-11ea-86dc-80a34b5a2b95.png)

I think this may be related to this issue: https://github.com/jupyterlab/jupyterlab-git/issues/723

When the `jupyter serverextension list` command  is ran in the notebook server, it says we have the `jupyterlab_git 0.20.0` version and when the `jupyter labextension list` command is ran, it says we have the `@jupyterlab/git v0.21.0-alpha.0` version. This issue could be caused because the server extension and the frontend extension don't have the same version.

This error only appears with the latest commit on master https://github.com/StatCan/kubeflow-containers/commit/cb2d3bc0caacb89d36c2615dabd33fba6e875511

**Comment by sylus** [comment]
I'm confused why the earlier commit doesn't have this problem? Do we need to lock both to a version?

**Comment by saffaalvi** [comment]
@sylus Not sure, building and running the latest commit locally doesn't have the problem either. It seems the @jupyterlab/git extension only gets updated in the latest commit when on Kubeflow. For now since there doesn't seem to be a compatible upgrade for the server extension, I think locking both to a version would be the best option.
