### ISSUE TITLE
Test Jupyter Book

### ISSUE THREAD

**Issue by frazs** [StatCan/kubeflow-containers#95]
Relates to https://github.com/StatCan/kubeflow-containers/issues/74

Install [Jupyter Book](https://jupyterbook.org/intro.html) in a notebook image. Get some sample .ipynb files (for example https://github.com/frazs/notebook-test/blob/master/visualization-tutorial.ipynb), confirm that publishing with graphs works, test out combining notebooks into a book, and see what happens when a book is uploaded on Minio (can it work as a book from there, or would Minio be limited to individual notebooks?). 

Refer to https://statcan.github.io/daaas/en/Storage for Minio setup/usage.

Edit: correction, wrote "sample notebook images" but meant "sample .ipynb files"!

**Comment by saffaalvi** [comment]
I tested the installation of Jupyter Book using the custom image for `minimal-notebook-cpu` with commit https://github.com/StatCan/kubeflow-containers/commit/efa8c2bad6e04b8004d14ca8c7190bcbc99e7338 on Kubeflow

**1. Installed Jupyter Book through terminal in image:** `pip install -U jupyter-book`
**2. Created a new book using their given template:** `jupyter-book create mybookname`
**3. Added sample `visualization-tutorial.ipynb` to `mybookname/` and updated `_toc.yml` to include this file** - if there are any errors in the notebook when running the cells, the book will not build so I removed all problematic cells from this notebook to build the book
**4. Built the book's HTML:** - `jupyter-book build mybookname/`, this generated a `_build` directory in `mybookname/`
**5. Opened the book by opening `intro.html` in new browser tab** - all the graphs were properly published and all the different notebooks are in the book as well (can navigate through the "Content in Jupyter Book" section which lists all the notebooks and files the book consists of)

When I would try to open the `.html` files in the browser, Google Chrome would not display these pages properly:
<img width="564" alt="Screen Shot 2020-08-14 at 3 41 07 PM" src="https://user-images.githubusercontent.com/57377830/90286818-9a887d00-de44-11ea-8105-81de3930e38d.png">

and when trying to navigate through the pages, would get the error:
<img width="373" alt="Screen Shot 2020-08-14 at 3 41 14 PM" src="https://user-images.githubusercontent.com/57377830/90286861-b2f89780-de44-11ea-8bf6-9217bc02da5a.png">

When I opened the `.html` files in Firefox though, the book displayed and worked perfectly. 

But, opening only the `index.html` file in both Firefox and Chrome gave the above error as well.

**Comment by saffaalvi** [comment]
Regarding uploading the book to Minio, you can either copy the whole book folder into Minio if you want all that extra information or even just the `mybookname/_build/html/` folder is enough. Then if you select the folder in Minio, "Download all as zip", and open the HTML files from the folder in your local computer (through Firefox), the book will display and work.

**Comment by saffaalvi** [comment]
Two more questions from @frazs :

**1. Does the "Blocking request from unknown origin" error appear in Chrome when you open the zip locally too, or only when it's opened as a new tab from JupyterLab in Kubeflow?**

The error does not appear when you open the zip locally.

**2. If you put the book in a Minio shared bucket, is there a way to browse through the book from Minio URLs, without downloading it as a zip?**

The only way I have found to browse through the book from Minio, is to create a shareable link of the object (each `.html` page) and view them all individually. You can't browse through links in the actual book though, as it will redirect you back to the `.html` file in Minio. Instead, you need to create a shareable link of all the objects and view them individually. Even then, when you open the individual `.html` files, it displays it in the simple view, not formatted correctly as in the picture shown for Google Chrome above.

**Comment by frazs** [comment]
Thank you Saffa!
